/** Which catalogue items have a photographed cutout, and where it came from.
 *
 * Generated by scripts/fetch- + process-charcuterie-images. Items missing here
 * fall back to the drawn motif, so the board never has a hole in it.
 *
 * Every source is CC0 or public domain — see data/charcuterie-images/manifest.json
 * for the full provenance record.
 */
export interface ItemPhoto { id: string; score: number; title: string; license: string; source: string; detail: string }

export const ITEM_PHOTOS: Record<string, ItemPhoto> = {
  "aged-gouda": {
    "id": "aged-gouda",
    "score": 40,
    "title": "File:Stolpersteine Gouda AG de Vrijestraat 18 (detail1).jpg",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://commons.wikimedia.org/w/index.php?curid=71961928"
  },
  "amaretti": {
    "id": "amaretti",
    "score": 92,
    "title": "BALLERIO, Osvaldo (1870-1942). Biscottini e Amaretti Delser, c. 1900.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/72185053@N00/49829134983"
  },
  "apple": {
    "id": "apple",
    "score": 92,
    "title": "Apple",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/57873306@N00/2286495290"
  },
  "apple-butter": {
    "id": "apple-butter",
    "score": 92,
    "title": "Condensing Apple Sauce to Apple Butter",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37996646802@N01/36398105465"
  },
  "apricot": {
    "id": "apricot",
    "score": 92,
    "title": "Pile fresh apricots",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6029278/photo-image-public-domain-fruit-food"
  },
  "apricot-preserve": {
    "id": "apricot-preserve",
    "score": 0,
    "title": "Supplies for home canning on table",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/93936679@N05/34639260193"
  },
  "baguette": {
    "id": "baguette",
    "score": 0,
    "title": "baroque",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://svgsilh.com/ffc107/image/1712561.html"
  },
  "balsamic-glaze": {
    "id": "balsamic-glaze",
    "score": 92,
    "title": "A vibrant Caprese salad made with alternating slices of fresh mozzarella and ripe tomatoes, topped with basil leaves and a drizzle of balsamic glaze, served on a white platter.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/519685c7ef/"
  },
  "basil": {
    "id": "basil",
    "score": 92,
    "title": "Fresh Basil!",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37996646802@N01/3787667468"
  },
  "bell-pepper": {
    "id": "bell-pepper",
    "score": 100,
    "title": "Fresh Red Sweet Pepper Vegetables",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/5966157/fresh-red-sweet-pepper-vegetables"
  },
  "biscotti": {
    "id": "biscotti",
    "score": 92,
    "title": "2011 11 02 pranzo e biscotti",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/72923835@N00/9366133994"
  },
  "blackberry": {
    "id": "blackberry",
    "score": 0,
    "title": "fresh-blackberries-on-white-background",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/65798313@N06/18934171116"
  },
  "blueberry": {
    "id": "blueberry",
    "score": 92,
    "title": "Blueberry Strawberry Mix",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/8398907@N02/5192360565"
  },
  "boursin": {
    "id": "boursin",
    "score": 100,
    "title": "Boursin-cheese-3494 1280",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://commons.wikimedia.org/w/index.php?curid=136571475"
  },
  "bresaola": {
    "id": "bresaola",
    "score": 92,
    "title": "Bresaola carpaccio with wild rockets",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/448445/free-photo-image-carpaccio-food-meat"
  },
  "brie": {
    "id": "brie",
    "score": 92,
    "title": "'Fromage de Brie'.",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37667416@N04/4306304496"
  },
  "brioche-toast": {
    "id": "brioche-toast",
    "score": 92,
    "title": "Toasted brioche",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/959642c1db/"
  },
  "burrata": {
    "id": "burrata",
    "score": 92,
    "title": "Burrata with tomato",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/3282815/free-photo-image-bread-burrata-cake"
  },
  "cambozola": {
    "id": "cambozola",
    "score": 100,
    "title": "Cambozola cheese 2",
    "license": "Public domain",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Cambozola_cheese_2.jpg"
  },
  "camembert": {
    "id": "camembert",
    "score": 92,
    "title": "'Magasin de perfectionement du fromage de Camembert'.",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37667416@N04/4306304760"
  },
  "candied-orange": {
    "id": "candied-orange",
    "score": 0,
    "title": "Candy colored candles",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/40632439@N00/24964224570"
  },
  "caper-berry": {
    "id": "caper-berry",
    "score": 0,
    "title": "Illustration Capparis spinosa0",
    "license": "Public domain",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Illustration_Capparis_spinosa0.jpg"
  },
  "carrot": {
    "id": "carrot",
    "score": 92,
    "title": "rainbow carrots from garden held in hand",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/491654d9c6/"
  },
  "cashew": {
    "id": "cashew",
    "score": 100,
    "title": "cashew nuts",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/171425013@N02/50254225402"
  },
  "champagne-grape": {
    "id": "champagne-grape",
    "score": 92,
    "title": "Moët & Chandon Champagne grapes",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6112343/photo-image-public-domain-plant-green"
  },
  "cheddar": {
    "id": "cheddar",
    "score": 0,
    "title": "Organic breakfast sandwich on onion bagel",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/7633518@N08/54096609638"
  },
  "cherry": {
    "id": "cherry",
    "score": 92,
    "title": "'Morpho Achilles & Cherries.' Blue-banded Morpho butterflies and Surinam cherries.",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/97123293@N07/16679614545"
  },
  "cherry-tomato": {
    "id": "cherry-tomato",
    "score": 92,
    "title": "Handful of Cherry Tomatoes",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/47121680@N00/48680268027"
  },
  "chestnut": {
    "id": "chestnut",
    "score": 92,
    "title": "Roasted chestnut",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/3287698/free-photo-image-bean-blossom-blur-background"
  },
  "chevre": {
    "id": "chevre",
    "score": 45,
    "title": "Bacon, spinach, roasted garlic and goat cheese scramble",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/77114776@N00/3713693238"
  },
  "chive": {
    "id": "chive",
    "score": 92,
    "title": "Siberian chives, Lower Lovetts Farm",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/11569642@N00/19634181248"
  },
  "choc-almond": {
    "id": "choc-almond",
    "score": 8,
    "title": "Finnish Sweeties #13: Tupla Kingsize",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/23408922@N07/13474648734"
  },
  "chocolate-truffle": {
    "id": "chocolate-truffle",
    "score": 92,
    "title": "Free chocolate truffles image",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/5905831/photo-image-background-public-domain-black"
  },
  "chorizo": {
    "id": "chorizo",
    "score": 0,
    "title": "Seafood Market: 'El asturiano'",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/62518311@N00/107864528"
  },
  "citrus": {
    "id": "citrus",
    "score": 40,
    "title": "Florida-Supreme-Court-2014",
    "license": "Public domain",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Florida-Supreme-Court-2014.jpg"
  },
  "clementine": {
    "id": "clementine",
    "score": 92,
    "title": "Clementines",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/40632439@N00/24507056225"
  },
  "comte": {
    "id": "comte",
    "score": 92,
    "title": "'Urne romaine trouvée dans le comté de Glocester'.",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37667416@N04/4615016144"
  },
  "coppa": {
    "id": "coppa",
    "score": 92,
    "title": "DAM1941 - Coppa allo Strudel",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/121131556@N06/29096281577"
  },
  "cornichon": {
    "id": "cornichon",
    "score": 92,
    "title": "Cornichon sauteur",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/87805257@N00/29604019834"
  },
  "cranberry-sauce": {
    "id": "cranberry-sauce",
    "score": 92,
    "title": "Food Cranberry Sauce",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/193916823@N05/51687785102"
  },
  "cream-cheese": {
    "id": "cream-cheese",
    "score": 0,
    "title": "Radisson Hotel Dinner Menu - DPLA - b36f60798d8a9735331c6e0e8847c2d2 (page 1)",
    "license": "Public domain",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Radisson_Hotel_Dinner_Menu_-_DPLA_-_b36f60798d8a9735331c6e0e8847c2d2_(page_1).jpg"
  },
  "cucumber": {
    "id": "cucumber",
    "score": 92,
    "title": "Watermelon, tomatoes, beets, beans, cucumber, onion, and gourd. J. Steckler Seed Co., L.t.d. (1899)",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/97123293@N07/14669011701"
  },
  "currants-red": {
    "id": "currants-red",
    "score": 92,
    "title": "Redcurrants",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/63058338@N02/46690154675"
  },
  "dark-chocolate": {
    "id": "dark-chocolate",
    "score": 92,
    "title": "Dark Chocolate",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://stocksnap.io/photo/dark-chocolate-ICYU9IFGSZ"
  },
  "date": {
    "id": "date",
    "score": 92,
    "title": "Medjool Dates",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/25802865@N08/55237678000"
  },
  "dill": {
    "id": "dill",
    "score": 92,
    "title": "Dill (Anethum graveolens), Dandelion (Taraxacum campylodes), Dodder (Cuscuta europaea), and Elecampanel ( Filipendula vulgaris). The British flora medica...(1838))",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/97123293@N07/15243075876"
  },
  "dried-apricot": {
    "id": "dried-apricot",
    "score": 100,
    "title": "Short drink with dried apricot",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/447928/free-photo-image-alcohol-alcoholic-appetite"
  },
  "dried-cherry": {
    "id": "dried-cherry",
    "score": 0,
    "title": "Jar Mug",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://stocksnap.io/photo/jar-mug-QRDORARYQV"
  },
  "dried-cranberry": {
    "id": "dried-cranberry",
    "score": 100,
    "title": "A dark wooden serving platter arranged with crackers, sliced deli meats, almonds, dried cranberries, a small bowl of dip, and herb-crusted cheese.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/33269d7733/"
  },
  "dried-fig": {
    "id": "dried-fig",
    "score": 100,
    "title": "Dried figs isolated on a white background",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/155753322@N06/41903829690"
  },
  "dried-pear": {
    "id": "dried-pear",
    "score": 0,
    "title": "Another Zero Dollar Project",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37996646802@N01/2523437258"
  },
  "dried-pineapple": {
    "id": "dried-pineapple",
    "score": 100,
    "title": "Getting ready to sample dried pineapple",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/93936679@N05/36894093872"
  },
  "dried-strawberry": {
    "id": "dried-strawberry",
    "score": 0,
    "title": "Finnish Sweeties #8: Fazer Strawberry and Raspberry in White and Dark Chocolate",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/23408922@N07/13044368385"
  },
  "edible-flowers": {
    "id": "edible-flowers",
    "score": 92,
    "title": "A slice of cake with white frosting, topped with blue and purple edible flowers, seeds, and nuts, sits on a white plate. A fork rests next to it on a wooden table, with a folded napkin beneath the fork.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/7006710dbd/"
  },
  "emmental": {
    "id": "emmental",
    "score": 92,
    "title": "14 .89/1.44C 31A Langnau im Emmental",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/13868867@N06/52477746410"
  },
  "epoisses": {
    "id": "epoisses",
    "score": 0,
    "title": "201907_0289",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/186165403@N05/50210044606"
  },
  "everything-cracker": {
    "id": "everything-cracker",
    "score": 48,
    "title": "Project 365 #290: 171010 Absolutely Crackers",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/23408922@N07/5089402435"
  },
  "fennel-frond": {
    "id": "fennel-frond",
    "score": 92,
    "title": "Swirling drops in fennel fronds",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/134468672@N06/34608871313"
  },
  "feta": {
    "id": "feta",
    "score": 92,
    "title": "Tara, Feta and Red Pepper and Melinzano dip at Ouzeri",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/35034347371@N01/12848031"
  },
  "fig": {
    "id": "fig",
    "score": 92,
    "title": "Fresh Figs",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://stocksnap.io/photo/fresh-figs-6OIDESBFHK"
  },
  "fig-jam": {
    "id": "fig-jam",
    "score": 40,
    "title": "Fig Tree, Sunnybank",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/60455048@N02/38370914672"
  },
  "focaccia": {
    "id": "focaccia",
    "score": 92,
    "title": "Focaccia",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/7633518@N08/54282311571"
  },
  "golden-raisin": {
    "id": "golden-raisin",
    "score": 92,
    "title": "Golden-brown spiral cinnamon roll buns with raisins and a glossy glaze cooling on a metal wire rack. Multiple freshly baked buns are arranged closely together.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/7736a28fbe/"
  },
  "grana-padano": {
    "id": "grana-padano",
    "score": 0,
    "title": "",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/5949037/free-public-domain-cc0-photo"
  },
  "grape-green": {
    "id": "grape-green",
    "score": 92,
    "title": "Green Grapes",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://stocksnap.io/photo/green-grapes-4ELIEQT8IV"
  },
  "grape-red": {
    "id": "grape-red",
    "score": 92,
    "title": "Red Grapes",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://stocksnap.io/photo/red-grapes-1S5SK2CJ0V"
  },
  "grissini": {
    "id": "grissini",
    "score": 92,
    "title": "Free baking homemade grissini snack",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/5918679/image-public-domain-food-free"
  },
  "gruyere": {
    "id": "gruyere",
    "score": 92,
    "title": "'Fabrication du fromage de Gruyère dans un chalet suisse, ou fromagerie des Alpes'.",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37667416@N04/4306335270"
  },
  "halva": {
    "id": "halva",
    "score": 92,
    "title": "halva",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/159532851@N07/29675367128"
  },
  "havarti": {
    "id": "havarti",
    "score": 8,
    "title": "Ham, cheese and tomato omelet",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/77114776@N00/3732521283"
  },
  "hazelnut": {
    "id": "hazelnut",
    "score": 92,
    "title": "Still life with plums, grapes and peaches in a wicker basket, with Cherries, Hazelnuts, a Beetle and a Butterfly on the Woodentabletop Beneath” Jacob van Hulsdonck - circa 1620 (Belgian, 1582 - 1647)",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/97123293@N07/15027916849"
  },
  "honeycomb": {
    "id": "honeycomb",
    "score": 92,
    "title": "Small Honey Jar with Honeycomb",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/184594136@N08/51330849013"
  },
  "humboldt-fog": {
    "id": "humboldt-fog",
    "score": 45,
    "title": "Little gem salad with Humboldt Fog goat cheese",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/7633518@N08/55159713657"
  },
  "hummus": {
    "id": "hummus",
    "score": 92,
    "title": "Home Made Hummus",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37996646802@N01/47033129421"
  },
  "jamon-iberico": {
    "id": "jamon-iberico",
    "score": 92,
    "title": "Jamón 100% ibérico de bellota (Etiqueta Negra) 'Monte Nevado' (Carbonero el Mayor. Segovia. España)",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/187577229@N08/54897404299"
  },
  "jamon-serrano": {
    "id": "jamon-serrano",
    "score": 92,
    "title": "Jamón Serrano 'Monte Nevado' (Carbonero el Mayor. Segovia. España",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/187577229@N08/54897148826"
  },
  "kalamata": {
    "id": "kalamata",
    "score": 40,
    "title": "Kalamata railstation",
    "license": "Public domain",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Kalamata_railstation.JPG"
  },
  "kumquat": {
    "id": "kumquat",
    "score": 92,
    "title": "Kumquats",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/25802865@N08/55447569698"
  },
  "landjaeger": {
    "id": "landjaeger",
    "score": 92,
    "title": "Team Landjäger auf der Flucht",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/87101523@N04/47061464311"
  },
  "lardo": {
    "id": "lardo",
    "score": 92,
    "title": "Lardo-bergamo-20231229 03",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://commons.wikimedia.org/w/index.php?curid=143689419"
  },
  "lychee": {
    "id": "lychee",
    "score": 92,
    "title": "lychees",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/171425013@N02/48060055446"
  },
  "macadamia": {
    "id": "macadamia",
    "score": 92,
    "title": "Glyhposate herbicide injury to macadamia (Macadamia integrifolia)",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/62295966@N07/14851227924"
  },
  "manchego": {
    "id": "manchego",
    "score": 92,
    "title": "Postres manchegos",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/135025598@N03/38432245661"
  },
  "mango-chutney": {
    "id": "mango-chutney",
    "score": 0,
    "title": "It Smells Great",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/43296902@N00/2395177570"
  },
  "marcona-almond": {
    "id": "marcona-almond",
    "score": 92,
    "title": "Port Wine Bonbon, Salted Marcona Almonds",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/187878392@N04/53178347237"
  },
  "marzipan": {
    "id": "marzipan",
    "score": 92,
    "title": "Closeup pile marzipan potatoes",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6021035/photo-image-public-domain-food-free"
  },
  "mascarpone": {
    "id": "mascarpone",
    "score": 92,
    "title": "A slice of tiramisu on a white plate, featuring layers of creamy mascarpone and coffee-soaked sponge, dusted with cocoa.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/9176a28f64/"
  },
  "melba-toast": {
    "id": "melba-toast",
    "score": 0,
    "title": "GCDA Week 2 Bread 03",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/75126686@N00/52866402028"
  },
  "melon": {
    "id": "melon",
    "score": 92,
    "title": "Stem-end, fungal rot of organically grown cantaloupe",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/62295966@N07/14997960058"
  },
  "membrillo": {
    "id": "membrillo",
    "score": 92,
    "title": "Membrillos del Perú",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/134894678@N07/27075823780"
  },
  "microgreens": {
    "id": "microgreens",
    "score": 92,
    "title": "Microgreen Emerging - Urban Agriculture",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/194676499@N06/52272915426"
  },
  "mint": {
    "id": "mint",
    "score": 92,
    "title": "Labour Day dinner - Pasta w/mint, pecorino and heirloom tomatoes and Halibut Steaks",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/35034347371@N01/383496"
  },
  "morbier": {
    "id": "morbier",
    "score": 92,
    "title": "Tancua, juste avant Morbier, Jura",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/96064256@N04/50117566352"
  },
  "mortadella": {
    "id": "mortadella",
    "score": 92,
    "title": "Mortadella bologna sticker, food illustration",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6553080/psd-sticker-public-domain-pink"
  },
  "mozzarella": {
    "id": "mozzarella",
    "score": 92,
    "title": "Tomatoes Bocconcini",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://stocksnap.io/photo/tomatoes-bocconcini-NC1DGJG544"
  },
  "mustard": {
    "id": "mustard",
    "score": 92,
    "title": "'Chateaubriand' of Marcho Farms Veal, Stuffed Jacobsen Orchards Crab Apple, Garden Turnips, La Ratte Potato Puree and Whole Grain Mustard Sauce",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/187878392@N04/52222768772"
  },
  "nectarine": {
    "id": "nectarine",
    "score": 92,
    "title": "Les nectarines",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/87805257@N00/36110167275"
  },
  "oat-cake": {
    "id": "oat-cake",
    "score": 92,
    "title": "Made oat cakes for breakfast.",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/57873306@N00/49626316443"
  },
  "olive-oil": {
    "id": "olive-oil",
    "score": 53,
    "title": "St Helena Superintendent Seeking Information Re Making Olive Oil",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/60455048@N02/41140031744"
  },
  "onion-jam": {
    "id": "onion-jam",
    "score": 0,
    "title": "Blue Cheese CRUNCH - Crunch&Co 2024-04-16",
    "license": "CC0",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Blue_Cheese_CRUNCH_-_Crunch%26Co_2024-04-16.jpg"
  },
  "parmesan-crisp": {
    "id": "parmesan-crisp",
    "score": 40,
    "title": "Feta parcels and parmesan shortbread in the oven",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/75126686@N00/52846914710"
  },
  "parmigiano": {
    "id": "parmigiano",
    "score": 0,
    "title": "Queso",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/62518311@N00/115094517"
  },
  "passionfruit": {
    "id": "passionfruit",
    "score": 92,
    "title": "Passionfruit: Cucumber mosaic virus",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/62295966@N07/14692287977"
  },
  "pate": {
    "id": "pate",
    "score": 40,
    "title": "Pork pate, country style, with mustard on a toasted everything bagel - Massachusetts",
    "license": "CC0",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Pork_pate,_country_style,_with_mustard_on_a_toasted_everything_bagel_-_Massachusetts.jpg"
  },
  "peach": {
    "id": "peach",
    "score": 92,
    "title": "Chewy would do anything for a peach!",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/36943025@N07/4705969219"
  },
  "pear": {
    "id": "pear",
    "score": 92,
    "title": "Asian pear",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/62295966@N07/15212122077"
  },
  "pecan": {
    "id": "pecan",
    "score": 92,
    "title": "Close candied pecan pralines",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/11524269/close-candied-pecan-pralines"
  },
  "pecorino": {
    "id": "pecorino",
    "score": 92,
    "title": "Labour Day dinner - Pasta w/mint, pecorino and heirloom tomatoes and Halibut Steaks",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/35034347371@N01/383496"
  },
  "peperoncini": {
    "id": "peperoncini",
    "score": 92,
    "title": "peperoncini stesi ad asciugare al sole",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/78368129@N02/18272297192"
  },
  "pepper-jelly": {
    "id": "pepper-jelly",
    "score": 92,
    "title": "Another Round of Chile Pepper Jelly",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37996646802@N01/31035895361"
  },
  "persimmon": {
    "id": "persimmon",
    "score": 92,
    "title": "Florda Jay in American Persimmon (Diospyros virginiana) Birds of America [double elephant folio edition], Audubon, J.J., (1826-1838) [J.J. Audubon]",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/97123293@N07/14743758050"
  },
  "physalis": {
    "id": "physalis",
    "score": 92,
    "title": "PHYSALIS 1- IMG_9722-7",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/181765699@N08/51794791918"
  },
  "pickled-onion": {
    "id": "pickled-onion",
    "score": 92,
    "title": "Top-down view of an Indian-style meal on a white square plate with mutton rogan josh, naan bread, white posho, and pickled red onions.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/41969c85e2/"
  },
  "pineapple": {
    "id": "pineapple",
    "score": 92,
    "title": "Pineapples",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/40632439@N00/16256685132"
  },
  "pink-peppercorn": {
    "id": "pink-peppercorn",
    "score": 0,
    "title": "",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/5961633/free-public-domain-cc0-photo"
  },
  "pistachio": {
    "id": "pistachio",
    "score": 100,
    "title": "Pistachios Nuts",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://stocksnap.io/photo/pistachios-nuts-D3JX2C0MW9"
  },
  "pita-chip": {
    "id": "pita-chip",
    "score": 92,
    "title": "Spinach artichoke dip appetizer with pita chips",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/5826329e00/"
  },
  "plum": {
    "id": "plum",
    "score": 92,
    "title": "Still life with plums, grapes and peaches in a wicker basket, with Cherries, Hazelnuts, a Beetle and a Butterfly on the Woodentabletop Beneath” Jacob van Hulsdonck - circa 1620 (Belgian, 1582 - 1647)",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/97123293@N07/15027916849"
  },
  "pomegranate": {
    "id": "pomegranate",
    "score": 92,
    "title": "pomegranate",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/171425013@N02/48917780562"
  },
  "prosciutto-cotto": {
    "id": "prosciutto-cotto",
    "score": 0,
    "title": "Cooked ham served on wooden boards",
    "license": "CC0",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Cooked_ham_served_on_wooden_boards.jpg"
  },
  "prune": {
    "id": "prune",
    "score": 100,
    "title": "Doyoboshi dried plum",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6038218/photo-image-public-domain-food-white"
  },
  "raclette": {
    "id": "raclette",
    "score": 92,
    "title": "Lausanne raclette (1)",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/30784528@N04/20864616311"
  },
  "radish": {
    "id": "radish",
    "score": 92,
    "title": "Fried egg on toast with cutting radishes pieces- Healthy breakfast",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/7356572fdf/"
  },
  "raspberry": {
    "id": "raspberry",
    "score": 92,
    "title": "Raspberry by P.J. Redouté (1833)",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/97123293@N07/19830225322"
  },
  "reblochon": {
    "id": "reblochon",
    "score": 92,
    "title": "Reblochon",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/85825630@N00/6993614719"
  },
  "roasted-pepper": {
    "id": "roasted-pepper",
    "score": 53,
    "title": "A spicy, richly seasoned chicken dish with vibrant green and red bell peppers and onions on a white plate, garnished with green onions, sits on a wooden table.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/3156a4a6f3/"
  },
  "romesco": {
    "id": "romesco",
    "score": 0,
    "title": "FEL INTERMEDIAR",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/26291296@N02/17157271431"
  },
  "roquefort": {
    "id": "roquefort",
    "score": 92,
    "title": "'La rue des caves, à Roquefort'.",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/37667416@N04/4306306688"
  },
  "rosemary": {
    "id": "rosemary",
    "score": 100,
    "title": "A large, shallow metal pan filled with a rich, dark dish featuring chunks of meat, rice, and vegetables. The dish is garnished with bright green chives, slices of red onion, and a sprig of rosemary, while a shiny spoon rests on the edge.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/24468150be/"
  },
  "rye-crisp": {
    "id": "rye-crisp",
    "score": 0,
    "title": "Knaeckebroed",
    "license": "Public domain",
    "source": "commons",
    "detail": "https://commons.wikimedia.org/wiki/File:Knaeckebroed.jpg"
  },
  "salchichon": {
    "id": "salchichon",
    "score": 92,
    "title": "Salchichón Gáldar - Leales.org (http://bit.ly/2rWqwjp)",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/148980001@N04/35173071055"
  },
  "seeded-crisp": {
    "id": "seeded-crisp",
    "score": 0,
    "title": "Chouchou",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/11234074@N05/10143697606"
  },
  "shortbread": {
    "id": "shortbread",
    "score": 92,
    "title": "Christmas shortbread",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/91387891@N07/15581894010"
  },
  "smoked-gouda": {
    "id": "smoked-gouda",
    "score": 92,
    "title": "Charcuterie board with smoke gouda, olives, pickles, and thin sliced pork.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/2836448377/"
  },
  "smoked-salmon": {
    "id": "smoked-salmon",
    "score": 92,
    "title": "Smoked salmon on bannock",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/38144472@N04/8137221313"
  },
  "snap-pea": {
    "id": "snap-pea",
    "score": 92,
    "title": "Sugar snap peas png, Japanese",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6314859/png-vintage-public-domain"
  },
  "sourdough": {
    "id": "sourdough",
    "score": 92,
    "title": "A grilled sourdough sandwich cut in half shows ham, tomato, greens, avocado, and melted cheddar, served with tomato soup on a wooden table.",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://wordpress.org/photos/photo/62769efa9e/"
  },
  "speck": {
    "id": "speck",
    "score": 92,
    "title": "[Lonely Speck] Milky Way over Ashurst Lake",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/10836653@N05/27606438314"
  },
  "starfruit": {
    "id": "starfruit",
    "score": 92,
    "title": "Alajuela's public market. Starfruit (la",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6073109/photo-image-public-domain-leaf-plant"
  },
  "strawberry": {
    "id": "strawberry",
    "score": 0,
    "title": "strawberries",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/42787780@N04/6984507532"
  },
  "sun-dried-tomato": {
    "id": "sun-dried-tomato",
    "score": 92,
    "title": "Spaghetti with Arugula and Sun-Dried Tomatoes",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/89882948@N05/51717771670"
  },
  "tapenade": {
    "id": "tapenade",
    "score": 40,
    "title": "26-Tulbagh Oakhurst Olives",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/76319087@N08/49780636873"
  },
  "tarragon": {
    "id": "tarragon",
    "score": 92,
    "title": "Turkish version of the Wonders of creation, Tarragon, lentil, and fox grapes, Walters Manuscript W.659, fol. 236a",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/39699193@N03/5888688970"
  },
  "thyme": {
    "id": "thyme",
    "score": 92,
    "title": "FOOD SHOT - SEARED VEAL LOIN WITH GRILLED VEGETABLES & THYME JUS",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/54550615@N03/13844905173"
  },
  "triple-creme": {
    "id": "triple-creme",
    "score": 0,
    "title": "Brie on a Shelf",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://commons.wikimedia.org/w/index.php?curid=143480014"
  },
  "truffle-honey": {
    "id": "truffle-honey",
    "score": 92,
    "title": "Marshalls Farm Liquid Honey Truffle with White Chocolate and Bee Pollen",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/187878392@N04/52310731066"
  },
  "turkish-delight": {
    "id": "turkish-delight",
    "score": 92,
    "title": "Turkish delight",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.rawpixel.com/image/6030472/turkish-delight-free-public-domain-cc0-photo"
  },
  "turkish-fig": {
    "id": "turkish-fig",
    "score": 92,
    "title": "Turkish version of the Wonders of creation, A wild fig tree and a walnut tree, Walters Manuscript W.659, fol. 208a",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/39699193@N03/5888681564"
  },
  "valdeon": {
    "id": "valdeon",
    "score": 92,
    "title": "Exposición de Joaquín Valdeón en la Universidad de Oviedo",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/46322086@N04/41156671071"
  },
  "water-cracker": {
    "id": "water-cracker",
    "score": 0,
    "title": "NoPetroPA-plastic-nurdles-public-domain-7793",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/9602574@N02/39755523943"
  },
  "watermelon": {
    "id": "watermelon",
    "score": 92,
    "title": "Fresh Watermelon Chunks in Ready-to-Eat Container",
    "license": "cc0",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/132795455@N08/17946427520"
  },
  "wensleydale-cranberry": {
    "id": "wensleydale-cranberry",
    "score": 8,
    "title": "Project 365 #341: 081213 Cheese Cake",
    "license": "pdm",
    "source": "openverse",
    "detail": "https://www.flickr.com/photos/23408922@N07/11260655666"
  }
};

export function photoFor(id: string): string | null {
  return ITEM_PHOTOS[id] ? `/charcuterie/items/${id}.webp` : null;
}

/** Below this the match is a guess — the review page lists these for a human. */
export const PHOTO_CONFIDENCE_FLOOR = 60;
