import type { Item } from "../types";

/** Cheese. Palettes are [base, mid, accent] and feed the motif
 *  generators; `cuts` is the how-to-make-it-look-good payload. */
export const CHEESES: Item[] = [
  {
    id: "brie",
    name: "Brie",
    cat: "cheese",
    palette: ["#f6ecd2", "#efe0b8", "#fffaf0"],
    motif: "wedge",
    tags: ["creamy", "buttery", "mild", "rich", "silky"],
    note: "The diplomat of the board — nobody has ever objected to brie.",
    loves: ["fig-jam", "baguette", "strawberry", "hot-honey", "dried-apricot"],
    cuts: [
      {
        name: "The M",
        how: "Cut the round into even triangles, then flip every other one so points alternate up and down. Close the row up until the edges touch and the whole thing reads as a zigzag.",
        motif: "mwave",
        flair: "Costs nothing beyond cutting it straight, and it's the difference between a wedge of cheese and a plated one.",
        effort: 1,
      },
      {
        name: "Crown Cut",
        how: "Leave the wheel whole, slice the top rind off in a disc and lift it away like a lid. The paste slumps outward as it warms.",
        motif: "round",
        flair: "Pour hot honey into the well and let it run over the sides.",
        effort: 2,
      },
      {
        name: "Wedge Fan",
        how: "Halve the wheel, then cut wedges from the centre point out. Fan them so every piece shows a stripe of rind.",
        motif: "wedge",
        effort: 1,
      },
      {
        name: "Baked Whole",
        how: "Score the top in a crosshatch, bake 15 min at 350°F, and set it on the board still in its dish. Everything else arranges around it.",
        motif: "round",
        effort: 3,
      },
    ],
  },
  {
    id: "camembert",
    name: "Camembert",
    cat: "cheese",
    palette: ["#f4e8cc", "#e9dab4", "#fdf8ec"],
    motif: "wedge",
    tags: ["creamy", "earthy", "funky", "rich", "bold"],
    note: "Brie's louder cousin — mushroomy, barnyard-adjacent, worth it.",
    loves: ["baguette", "apple", "walnut", "onion-jam"],
    cuts: [
      {
        name: "The M",
        how: "Cut the round into even triangles, then flip every other one so points alternate up and down. Close the row up until the edges touch and the whole thing reads as a zigzag.",
        motif: "mwave",
        flair: "Costs nothing beyond cutting it straight, and it's the difference between a wedge of cheese and a plated one.",
        effort: 1,
      },
      {
        name: "Wedge Fan",
        how: "Cut from the centre like a pie, eight wedges, fanned in a quarter-circle.",
        motif: "wedge",
        effort: 1,
      },
      {
        name: "Spoon Service",
        how: "Take the top rind off a room-temp wheel and leave a spoon in it. Let people dig.",
        motif: "round",
        effort: 1,
      },
    ],
  },
  {
    id: "triple-creme",
    name: "Triple-crème",
    cat: "cheese",
    palette: ["#fbf3dc", "#f2e6c0", "#fffdf5"],
    motif: "wedge",
    tags: ["creamy", "buttery", "rich", "silky", "mild"],
    note: "Delice de Bourgogne and friends. Absurdly rich; a little goes far.",
    loves: ["champagne-grape", "water-cracker", "honeycomb", "raspberry"],
    cuts: [
      {
        name: "Thick Batons",
        how: "Cut cold into finger-width batons, then let them come to room temp on the board. They'll soften into shape.",
        motif: "batons",
        effort: 1,
      },
      {
        name: "Half-Wheel Slump",
        how: "Halve it, cut side up, and do nothing else. It will collapse gracefully over 20 minutes.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "burrata",
    name: "Burrata",
    cat: "cheese",
    palette: ["#fdfbf4", "#f0ece0", "#ffffff"],
    motif: "round",
    tags: ["creamy", "buttery", "silky", "mild", "rich"],
    note: "A mozzarella purse full of cream. The board's showstopper.",
    loves: ["peach", "olive-oil", "basil", "sourdough", "prosciutto", "fig"],
    cuts: [
      {
        name: "Torn Open",
        how: "Set it whole in a shallow bowl and tear the top open at the table so the cream floods out. Salt, pepper, oil.",
        motif: "round",
        flair: "Tear it *after* guests arrive. This is a spectator sport.",
        effort: 1,
      },
      {
        name: "Draped Halves",
        how: "Halve it, cut side up, and drape a peach slice or a ribbon of prosciutto over each half.",
        motif: "halved",
        effort: 2,
      },
    ],
  },
  {
    id: "mozzarella",
    name: "Bocconcini",
    cat: "cheese",
    palette: ["#fbf8ee", "#eae5d6", "#ffffff"],
    motif: "cluster",
    tags: ["creamy", "mild", "buttery", "light", "silky"],
    note: "Little mozzarella balls. Neutral, bouncy, endlessly agreeable.",
    loves: ["basil", "olive-oil", "peach", "prosciutto"],
    cuts: [
      {
        name: "Marinated Pearls",
        how: "Toss in olive oil, lemon zest, chilli flake and torn basil an hour ahead. Pile them in a small bowl, glossy.",
        motif: "cluster",
        effort: 2,
      },
      {
        name: "Skewered",
        how: "Thread one ball, one basil leaf, one folded ribbon of prosciutto onto a short pick. Lay them in a row like soldiers.",
        motif: "cluster",
        effort: 2,
      },
    ],
  },
  {
    id: "ricotta",
    name: "Whipped ricotta",
    cat: "cheese",
    palette: ["#fdfaf2", "#efe9dc", "#ffffff"],
    motif: "bowl",
    tags: ["creamy", "mild", "light", "spreadable", "silky"],
    note: "Whip it two minutes and it goes from grainy to cloud.",
    loves: ["honeycomb", "nduja", "peach", "sourdough", "pistachio", "fig"],
    cuts: [
      {
        name: "Swooshed Bowl",
        how: "Whip with a little olive oil and salt, spoon into a wide shallow bowl, and drag the back of the spoon through it to make a valley.",
        motif: "bowl",
        flair: "Fill the valley with hot honey and cracked pepper.",
        effort: 2,
      },
    ],
  },
  {
    id: "chevre",
    name: "Goat cheese",
    cat: "cheese",
    palette: ["#fcfaf3", "#ebe6d8", "#ffffff"],
    motif: "round",
    tags: ["creamy", "acidic", "grassy", "spreadable", "bold"],
    note: "Bright, chalky, faintly barnyard — the acid that resets your mouth.",
    loves: ["honeycomb", "thyme", "strawberry", "peach", "pomegranate"],
    cuts: [
      {
        name: "Herb-Rolled Log",
        how: "Roll the log in chopped herbs, cracked pepper and lemon zest, then slice into coins with dental floss — a knife smears it.",
        motif: "shingle",
        flair: "Floss, not a knife. Every time.",
        effort: 2,
      },
      {
        name: "Torn Craggy",
        how: "Break it into rough craggy lumps with your fingers and scatter. Ugly on purpose, catches honey beautifully.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "boursin",
    name: "Boursin",
    cat: "cheese",
    palette: ["#f7f3e4", "#dfe3c4", "#8fa06a"],
    motif: "bowl",
    tags: ["creamy", "garlicky", "herbal", "spreadable", "rich"],
    note: "Garlic and herb, straight from the foil. No notes, no shame.",
    loves: ["water-cracker", "cornichon", "grissini"],
    cuts: [
      {
        name: "Puck, Scored",
        how: "Set the puck out whole and score a crosshatch across the top so the first person doesn't have to commit.",
        motif: "round",
        effort: 1,
      },
    ],
  },
  {
    id: "feta",
    name: "Feta",
    cat: "cheese",
    palette: ["#fbf9f2", "#e8e4d6", "#ffffff"],
    motif: "cube",
    tags: ["salty", "briny", "crumbly", "acidic", "bold"],
    note: "Buy it in brine, in a block. The pre-crumbled stuff is sawdust.",
    loves: ["castelvetrano", "mint", "honeycomb", "pomegranate", "melon"],
    cuts: [
      {
        name: "Marinated Cubes",
        how: "Cube the block, bathe in olive oil with oregano, lemon peel and chilli. Serve in the oil.",
        motif: "cube",
        effort: 2,
      },
      {
        name: "Slab & Honey",
        how: "One thick slab, left whole, drizzled with honey and cracked pepper. People will break bits off it.",
        motif: "cube",
        effort: 1,
      },
    ],
  },
  {
    id: "manchego",
    name: "Manchego",
    cat: "cheese",
    palette: ["#f0dc9e", "#e0c47c", "#4a3b28"],
    motif: "wedge",
    tags: ["nutty", "firm", "salty", "buttery", "bold"],
    note: "Sheep's milk, basketweave rind, tastes like toasted almonds.",
    loves: ["membrillo", "marcona-almond", "chorizo", "castelvetrano"],
    cuts: [
      {
        name: "The M",
        how: "Cut the round into even triangles, then flip every other one so points alternate up and down. Close the row up until the edges touch and the whole thing reads as a zigzag.",
        motif: "mwave",
        flair: "Costs nothing beyond cutting it straight, and it's the difference between a wedge of cheese and a plated one.",
        effort: 1,
      },
      {
        name: "Classic Triangles",
        how: "Cut the wedge into thin triangles, rind on, and shingle them so the dark rind stripes repeat down the row.",
        motif: "shingle",
        flair: "That rind stripe is free graphic design. Use it.",
        effort: 1,
      },
      {
        name: "Manchego & Membrillo Stacks",
        how: "Top each triangle with a matching triangle of quince paste. Stack them in a leaning tower.",
        motif: "stack",
        effort: 2,
      },
    ],
  },
  {
    id: "aged-gouda",
    name: "Aged gouda",
    cat: "cheese",
    palette: ["#e0b25e", "#c9954a", "#7a4f22"],
    motif: "crumble",
    tags: ["nutty", "sweet", "umami", "firm", "crumbly", "bold"],
    note: "Butterscotch and crunchy tyrosine crystals. Genuinely candy-like.",
    loves: ["dark-chocolate", "dried-apricot", "mustard", "walnut", "date"],
    cuts: [
      {
        name: "The M",
        how: "Cut the round into even triangles, then flip every other one so points alternate up and down. Close the row up until the edges touch and the whole thing reads as a zigzag.",
        motif: "mwave",
        flair: "Costs nothing beyond cutting it straight, and it's the difference between a wedge of cheese and a plated one.",
        effort: 1,
      },
      {
        name: "Rustic Shards",
        how: "Drive a short cheese pick in at an angle and lever chunks off. Never slice a gouda this old — you want the fracture.",
        motif: "crumble",
        flair: "The uneven edges catch the light. That's the whole point.",
        effort: 1,
      },
    ],
  },
  {
    id: "young-gouda",
    name: "Young gouda",
    cat: "cheese",
    palette: ["#f5d98f", "#e8c46e", "#c8452f"],
    motif: "cube",
    tags: ["mild", "buttery", "firm", "sweet", "creamy"],
    note: "The red-wax one. Sweet, springy, the kid-friendly pick.",
    loves: ["apple", "mustard", "water-cracker"],
    cuts: [
      {
        name: "Domino Rows",
        how: "Cut slabs, then dominoes, and stand them on edge in a leaning row so they cascade.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "cheddar",
    name: "Sharp cheddar",
    cat: "cheese",
    palette: ["#eaa646", "#d98c31", "#b56a1e"],
    motif: "cube",
    tags: ["salty", "firm", "bold", "umami", "buttery"],
    note: "A two-year cheddar is tangy enough to stand up to anything.",
    loves: ["apple", "mustard", "onion-jam", "oat-cake", "walnut"],
    cuts: [
      {
        name: "Fat Batons",
        how: "Cut into thick fingers rather than thin slices — cheddar dries out fast at a thin gauge.",
        motif: "batons",
        effort: 1,
      },
      {
        name: "Snapped Shards",
        how: "Score a slab and snap it by hand into irregular planes. Scatter, don't align.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "clothbound-cheddar",
    name: "Clothbound cheddar",
    cat: "cheese",
    palette: ["#e6c06a", "#d3a94f", "#6b5334"],
    motif: "crumble",
    tags: ["earthy", "nutty", "crumbly", "bold", "umami"],
    note: "Wrapped in cloth and aged in a cave. Tastes like a barn, lovingly.",
    loves: ["apple", "onion-jam", "walnut", "oat-cake"],
    cuts: [
      {
        name: "The M",
        how: "Cut the round into even triangles, then flip every other one so points alternate up and down. Close the row up until the edges touch and the whole thing reads as a zigzag.",
        motif: "mwave",
        flair: "Costs nothing beyond cutting it straight, and it's the difference between a wedge of cheese and a plated one.",
        effort: 1,
      },
      {
        name: "Craggy Chunks",
        how: "Break along the natural crumble lines. Leave the cloth rind on one face for contrast.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "gruyere",
    name: "Gruyère",
    cat: "cheese",
    palette: ["#efd08a", "#dcb765", "#a07c3c"],
    motif: "batons",
    tags: ["nutty", "salty", "firm", "umami", "rich"],
    note: "Alpine, brothy, faintly sweet. The melting cheese that also slices.",
    loves: ["cornichon", "apple", "walnut", "grissini", "pear"],
    cuts: [
      {
        name: "Alpine Batons",
        how: "Cut into long batons and stack them log-cabin style, two by two, into a little tower.",
        motif: "batons",
        flair: "Height. Nobody builds up, and it's the easiest win on the board.",
        effort: 2,
      },
    ],
  },
  {
    id: "comte",
    name: "Comté",
    cat: "cheese",
    palette: ["#eed394", "#dcbb6c", "#9c763a"],
    motif: "wedge",
    tags: ["nutty", "sweet", "firm", "umami", "rich"],
    note: "Brown butter and hazelnut. Ask for an 18-month if they have it.",
    loves: ["walnut", "apple", "cornichon", "pear", "grissini"],
    cuts: [
      {
        name: "The M",
        how: "Cut the round into even triangles, then flip every other one so points alternate up and down. Close the row up until the edges touch and the whole thing reads as a zigzag.",
        motif: "mwave",
        flair: "Costs nothing beyond cutting it straight, and it's the difference between a wedge of cheese and a plated one.",
        effort: 1,
      },
      {
        name: "Thick Triangles",
        how: "Cut generous triangles — thin slices lose the crystalline crunch that makes a good Comté.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "parmigiano",
    name: "Parmigiano-Reggiano",
    cat: "cheese",
    palette: ["#efdfab", "#dfc98a", "#b39a5c"],
    motif: "crumble",
    tags: ["salty", "umami", "nutty", "crumbly", "bold"],
    note: "Crystalline, savoury, the most umami thing on the board.",
    loves: ["honeycomb", "prosciutto", "pear", "walnut"],
    cuts: [
      {
        name: "Broken Rubble",
        how: "Never slice it. Push an almond-shaped Parmesan knife into the block and twist off craggy chunks.",
        motif: "crumble",
        flair: "Drizzle the pile with honey. Salty-sweet, ancient, undefeated.",
        effort: 2,
      },
    ],
  },
  {
    id: "pecorino",
    name: "Pecorino",
    cat: "cheese",
    palette: ["#f2e7c2", "#e2d3a3", "#3c3a33"],
    motif: "wedge",
    tags: ["salty", "firm", "peppery", "bold", "umami"],
    note: "Sheep's milk, sharper and saltier than Parm, with a black rind.",
    loves: ["honeycomb", "pear", "olive-oil"],
    cuts: [
      {
        name: "The M",
        how: "Cut the round into even triangles, then flip every other one so points alternate up and down. Close the row up until the edges touch and the whole thing reads as a zigzag.",
        motif: "mwave",
        flair: "Costs nothing beyond cutting it straight, and it's the difference between a wedge of cheese and a plated one.",
        effort: 1,
      },
      {
        name: "Rind-Striped Wedges",
        how: "Cut thin wedges keeping the black rind on every piece, then fan them so the dark edge repeats.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "gorgonzola-dolce",
    name: "Gorgonzola dolce",
    cat: "cheese",
    palette: ["#f6f1de", "#dfe0cb", "#5f7d86"],
    motif: "bowl",
    tags: ["funky", "creamy", "spreadable", "salty", "bold"],
    note: "The gateway blue — sweet, spoonable, barely spicy.",
    loves: ["honeycomb", "pear", "peach", "walnut", "date", "fig"],
    cuts: [
      {
        name: "Spooned Quenelle",
        how: "It's too soft to cut. Scoop with two warm spoons into an oval and set it on a slate tile.",
        motif: "bowl",
        effort: 2,
      },
    ],
  },
  {
    id: "roquefort",
    name: "Roquefort",
    cat: "cheese",
    palette: ["#f4f2e6", "#dcded0", "#4e7284"],
    motif: "crumble",
    tags: ["funky", "salty", "crumbly", "bold", "rich"],
    note: "Sheep's milk blue, cave-aged, aggressively delicious.",
    loves: ["honeycomb", "pear", "walnut", "date", "dried-fig"],
    cuts: [
      {
        name: "Crumbled Drift",
        how: "Crumble into a loose drift rather than a pile — a blue this strong wants to be taken in small amounts.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "stilton",
    name: "Stilton",
    cat: "cheese",
    palette: ["#f6efd6", "#e2ddc0", "#546e79"],
    motif: "wedge",
    tags: ["funky", "salty", "crumbly", "earthy", "bold"],
    note: "The Christmas blue. Firmer than most, tastes of toasted nuts.",
    loves: ["date", "walnut", "pear", "oat-cake", "honeycomb"],
    cuts: [
      {
        name: "Wedge, Scooped",
        how: "Serve the wedge upright with a small spoon and let people scoop from the cut face.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "taleggio",
    name: "Taleggio",
    cat: "cheese",
    palette: ["#f7ebcc", "#e8d3a6", "#d08a52"],
    motif: "cube",
    tags: ["funky", "creamy", "rich", "earthy", "bold"],
    note: "Washed rind. Smells like a locker room, tastes like brown butter.",
    loves: ["pear", "honeycomb", "sourdough", "walnut"],
    cuts: [
      {
        name: "Warm Squares",
        how: "Cut into squares an hour before serving. The paste near the rind goes molten at room temperature.",
        motif: "cube",
        effort: 1,
      },
    ],
  },
  {
    id: "epoisses",
    name: "Époisses",
    cat: "cheese",
    palette: ["#f2d69a", "#e2b96f", "#c96a2c"],
    motif: "bowl",
    tags: ["funky", "creamy", "rich", "bold", "spreadable"],
    note: "Washed in brandy. Banned on French public transport, allegedly.",
    loves: ["baguette", "apple", "walnut"],
    cuts: [
      {
        name: "Lid Off, Spoon In",
        how: "Leave it in its wooden box, cut the top rind away and hand over a spoon. Do not attempt to slice this.",
        motif: "bowl",
        flair: "Set the box on the board. The box is part of the look.",
        effort: 1,
      },
    ],
  },
  {
    id: "halloumi",
    name: "Grilled halloumi",
    cat: "cheese",
    palette: ["#f8f2e2", "#e9e0c8", "#c98b46"],
    motif: "shingle",
    tags: ["salty", "firm", "smoky", "chewy", "bold"],
    note: "Squeaky, grillable, holds its shape under fire.",
    loves: ["honeycomb", "mint", "melon"],
    cuts: [
      {
        name: "Charred Planks",
        how: "Slice thick, grill hard on both sides until striped, then hit with lemon and honey while still hot.",
        motif: "shingle",
        flair: "Serve warm. One warm thing on a cold board is a whole personality.",
        effort: 3,
      },
    ],
  },
  {
    id: "smoked-gouda",
    name: "Smoked gouda",
    cat: "cheese",
    palette: ["#e2b478", "#cd9757", "#8a5a2c"],
    motif: "cube",
    tags: ["smoky", "firm", "buttery", "umami", "bold"],
    note: "Real smoke, not liquid smoke. Check the rind is brown, not orange.",
    loves: ["apple", "mustard", "pecan", "onion-jam"],
    cuts: [
      {
        name: "Two-Tone Slices",
        how: "Slice so each piece keeps the dark smoked edge against the pale interior.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "havarti",
    name: "Havarti",
    cat: "cheese",
    palette: ["#f7e9be", "#ecd9a2", "#fffaf0"],
    motif: "shingle",
    tags: ["mild", "buttery", "creamy", "light", "silky"],
    note: "Soft, buttery, uncontroversial. The one the kids will eat.",
    loves: ["water-cracker", "apple", "grape-red"],
    cuts: [
      {
        name: "Folded Ribbons",
        how: "Slice thin and fold each slice in half twice into a soft triangle, then shingle them.",
        motif: "drape",
        effort: 1,
      },
    ],
  },

  // ─── Added in the expansion ────────────────────────────────────────────────
  {
    id: "mascarpone",
    name: "Mascarpone",
    cat: "cheese",
    palette: ["#fdfaf0", "#f2ecd8", "#ffffff"],
    motif: "bowl",
    tags: ["creamy", "sweet", "rich", "silky", "mild"],
    note: "Barely a cheese — closer to set cream. Sweeten it and it's dessert.",
    loves: ["strawberry", "dark-chocolate", "amaretti", "honeycomb", "fig"],
    cuts: [
      {
        name: "Whipped with Honey",
        how: "Beat with honey and a scrape of vanilla until it holds a peak, then spoon into a bowl and dust with cocoa.",
        motif: "bowl",
        effort: 2,
      },
    ],
  },
  {
    id: "cream-cheese",
    name: "Cream cheese block",
    cat: "cheese",
    palette: ["#fdfbf5", "#f0ebdd", "#ffffff"],
    motif: "cube",
    tags: ["creamy", "acidic", "spreadable", "mild", "rich"],
    note: "A whole block, straight from the foil. The pepper-jelly delivery system.",
    loves: ["pepper-jelly", "water-cracker", "smoked-salmon", "chive"],
    cuts: [
      {
        name: "Block & Flood",
        how: "Set the block down whole and pour pepper jelly over it so it pools around the base. One spreader, no plating.",
        motif: "cube",
        flair: "Zero effort, and it is always the first thing to disappear.",
        effort: 1,
      },
    ],
  },
  {
    id: "labneh",
    name: "Labneh",
    cat: "cheese",
    palette: ["#fdfbf4", "#eeead9", "#8fa04c"],
    motif: "bowl",
    tags: ["creamy", "acidic", "spreadable", "light", "grassy"],
    note: "Strained yoghurt, thick and tangy. Cuts through everything rich near it.",
    loves: ["olive-oil", "lavash", "pomegranate", "mint", "cucumber"],
    cuts: [
      {
        name: "Swooshed & Pooled",
        how: "Spread in a shallow bowl, make a well with the back of a spoon, and flood it with olive oil, sumac and mint.",
        motif: "bowl",
        effort: 2,
      },
    ],
  },
  {
    id: "humboldt-fog",
    name: "Humboldt Fog",
    cat: "cheese",
    palette: ["#fbf8ee", "#e6e2d4", "#4a4a48"],
    motif: "wedge",
    tags: ["creamy", "acidic", "earthy", "grassy", "bold"],
    note: "Goat cheese with a seam of vegetable ash through the middle. Striking.",
    loves: ["honeycomb", "fig", "seeded-crisp", "pear"],
    cuts: [
      {
        name: "Ash-Line Wedges",
        how: "Cut wedges straight down so every piece shows the dark stripe. The line is the entire visual argument for this cheese.",
        motif: "wedge",
        flair: "Face the cut edges outward so guests see the seam.",
        effort: 1,
      },
    ],
  },
  {
    id: "bucheron",
    name: "Bûcheron",
    cat: "cheese",
    palette: ["#fbf9f0", "#e8e3d2", "#f7f4ea"],
    motif: "shingle",
    tags: ["creamy", "acidic", "grassy", "crumbly", "bold"],
    note: "Aged goat log — molten just under the rind, chalky in the centre.",
    loves: ["honeycomb", "thyme", "walnut", "apricot-preserve"],
    cuts: [
      {
        name: "Thick Coins",
        how: "Slice into fat coins with floss so you keep both textures in every piece.",
        motif: "shingle",
        effort: 2,
      },
    ],
  },
  {
    id: "cambozola",
    name: "Cambozola",
    cat: "cheese",
    palette: ["#f8f4e2", "#e4e2ca", "#6b8290"],
    motif: "wedge",
    tags: ["creamy", "funky", "rich", "mild", "silky"],
    note: "Brie crossed with a gentle blue. The blue for people who say they hate blue.",
    loves: ["pear", "honeycomb", "walnut", "baguette"],
    cuts: [
      {
        name: "Soft Wedges",
        how: "Cut cold into wedges, then let them warm — the paste slumps and the blue veins bleed slightly.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "valdeon",
    name: "Valdeón",
    cat: "cheese",
    palette: ["#f2eedc", "#dcdcc4", "#4e6e7c"],
    motif: "crumble",
    tags: ["funky", "salty", "bold", "crumbly", "spicy"],
    note: "Spanish blue wrapped in sycamore leaves. Aggressive and wonderful.",
    loves: ["membrillo", "walnut", "date", "honeycomb"],
    cuts: [
      {
        name: "Served in its Leaf",
        how: "Unwrap only the top and serve it sitting in the leaf. The wrapper is the plating.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "munster",
    name: "Munster",
    cat: "cheese",
    palette: ["#f6e6c2", "#e6cf9e", "#d4834a"],
    motif: "wedge",
    tags: ["funky", "creamy", "bold", "rich", "earthy"],
    note: "Washed rind from Alsace. Pungent enough to need its own postcode.",
    loves: ["baguette", "apple", "pickled-onion", "rye-crisp"],
    cuts: [
      {
        name: "Warm Wedges",
        how: "Cut wedges and leave them out a full hour — cold Munster tastes of nothing and smells of everything.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "reblochon",
    name: "Reblochon",
    cat: "cheese",
    palette: ["#f7ecce", "#e8d6ac", "#c9a065"],
    motif: "wedge",
    tags: ["creamy", "nutty", "earthy", "rich", "silky"],
    note: "Savoyard, supple, faintly farmyard. Melts at the mere suggestion of warmth.",
    loves: ["cornichon", "baguette", "speck", "apple"],
    cuts: [
      {
        name: "Half-Wheel",
        how: "Halve the disc and lay both halves cut-side up so the paste sags outward.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "raclette",
    name: "Raclette",
    cat: "cheese",
    palette: ["#f5dfa2", "#e4c87e", "#b08a4a"],
    motif: "shingle",
    tags: ["nutty", "salty", "rich", "umami", "firm"],
    note: "Built to be melted and scraped. Serving it cold is a missed opportunity.",
    loves: ["cornichon", "pickled-onion", "baguette", "speck"],
    cuts: [
      {
        name: "Melted & Scraped",
        how: "Melt the cut face under a grill and scrape the molten sheet straight onto the board next to the pickles.",
        motif: "drape",
        flair: "Do it at the table. It is pure theatre and takes ninety seconds.",
        effort: 3,
      },
    ],
  },
  {
    id: "emmental",
    name: "Emmental",
    cat: "cheese",
    palette: ["#f7e4a8", "#e8d089", "#fffdf2"],
    motif: "cube",
    tags: ["nutty", "mild", "firm", "sweet", "buttery"],
    note: "The one with the holes. Sweet, mild, and structurally amusing.",
    loves: ["apple", "cornichon", "grissini", "mustard"],
    cuts: [
      {
        name: "Holes Facing Out",
        how: "Cut slabs so the holes show on the face, then stand them on edge in a row.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "provolone",
    name: "Provolone piccante",
    cat: "cheese",
    palette: ["#f7eac6", "#e8d5a0", "#c9a35e"],
    motif: "batons",
    tags: ["salty", "firm", "spicy", "umami", "bold"],
    note: "Aged provolone, sharp enough to bite back. Not the sandwich stuff.",
    loves: ["soppressata", "genoa", "peperoncini", "giardiniera"],
    cuts: [
      {
        name: "Snapped Batons",
        how: "Cut fat batons and pile them crosswise so they build a little height.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "grana-padano",
    name: "Grana Padano",
    cat: "cheese",
    palette: ["#efe0a8", "#dfcb88", "#b39a5c"],
    motif: "crumble",
    tags: ["salty", "umami", "nutty", "crumbly", "firm"],
    note: "Parmigiano's easier-going cousin, and a good deal cheaper.",
    loves: ["honeycomb", "balsamic-glaze", "prosciutto", "pear"],
    cuts: [
      {
        name: "Levered Chunks",
        how: "Twist chunks off with a stubby knife — the fracture face is the point.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "mimolette",
    name: "Mimolette",
    cat: "cheese",
    palette: ["#e8862c", "#d06e18", "#8a4a1c"],
    motif: "crumble",
    tags: ["nutty", "salty", "firm", "umami", "bold"],
    note: "Shocking orange, cratered rind, tastes of butterscotch. Aged by mites.",
    loves: ["mustard", "apple", "walnut", "cornichon"],
    cuts: [
      {
        name: "Bright Shards",
        how: "Break into shards. Nothing else on the board is this colour, so give it room.",
        motif: "crumble",
        flair: "It reads as neon against a dark board. Use it where you need a jolt.",
        effort: 1,
      },
    ],
  },
  {
    id: "morbier",
    name: "Morbier",
    cat: "cheese",
    palette: ["#f7e8c0", "#e6d3a2", "#4a4a44"],
    motif: "wedge",
    tags: ["creamy", "earthy", "mild", "rich", "silky"],
    note: "Two curds with a stripe of ash between them. Made for photographs.",
    loves: ["baguette", "apple", "cornichon", "walnut"],
    cuts: [
      {
        name: "Stripe-Forward Wedges",
        how: "Cut so the black line runs through every wedge, then fan them with the stripe repeating.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "ossau-iraty",
    name: "Ossau-Iraty",
    cat: "cheese",
    palette: ["#f2dfa8", "#e0c884", "#a07c48"],
    motif: "wedge",
    tags: ["nutty", "buttery", "firm", "mild", "rich"],
    note: "Basque sheep's milk. Gentle, grassy, and quietly one of the best.",
    loves: ["membrillo", "cherry", "marcona-almond", "honeycomb"],
    cuts: [
      {
        name: "Thin Triangles",
        how: "Slice thin and pair each triangle with black cherry jam — the traditional Basque partner.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "idiazabal",
    name: "Idiazábal",
    cat: "cheese",
    palette: ["#f0d99c", "#dcc078", "#7a5230"],
    motif: "wedge",
    tags: ["smoky", "nutty", "firm", "salty", "bold"],
    note: "Smoked Basque sheep's cheese. Tastes faintly of a wood fire.",
    loves: ["membrillo", "jamon-iberico", "marcona-almond", "castelvetrano"],
    cuts: [
      {
        name: "Rind-On Wedges",
        how: "Keep the burnished rind on every wedge — it carries most of the smoke.",
        motif: "wedge",
        effort: 1,
      },
    ],
  },
  {
    id: "tomme",
    name: "Tomme de Savoie",
    cat: "cheese",
    palette: ["#eee0b8", "#dcc999", "#8a8074"],
    motif: "cube",
    tags: ["earthy", "nutty", "mild", "firm", "creamy"],
    note: "Thick grey mould rind, mellow paste. Tastes like a cellar, in a good way.",
    loves: ["apple", "walnut", "cornichon", "rye-crisp"],
    cuts: [
      {
        name: "Rind-On Squares",
        how: "Cut squares and leave the woolly grey rind on. It's edible and it's the whole character.",
        motif: "cube",
        effort: 1,
      },
    ],
  },
  {
    id: "asiago",
    name: "Asiago d'allevo",
    cat: "cheese",
    palette: ["#f2e2b4", "#e0cd94", "#b09a68"],
    motif: "crumble",
    tags: ["nutty", "salty", "firm", "umami", "mild"],
    note: "Aged Asiago, dry and savoury. The workhorse hard cheese.",
    loves: ["honeycomb", "prosciutto", "grape-red", "mustard"],
    cuts: [
      {
        name: "Broken Nuggets",
        how: "Snap into rough nuggets rather than slicing; it's too crumbly to cut cleanly.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "wensleydale-cranberry",
    name: "Wensleydale & cranberry",
    cat: "cheese",
    palette: ["#fbf6e4", "#eee7cc", "#c2304a"],
    motif: "crumble",
    tags: ["creamy", "acidic", "sweet", "crumbly", "fruity"],
    note: "Crumbly white cheese studded with cranberries. Cheerfully unserious.",
    loves: ["oat-cake", "apple", "shortbread", "pear"],
    cuts: [
      {
        name: "Crumbled Rubble",
        how: "Break it up so the red flecks scatter through the pile rather than hiding inside a slab.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
];
