import type { Item } from "../types";

/** Nuts, sweets, herbs. Palettes are [base, mid, accent] and feed the motif
 *  generators; `cuts` is the how-to-make-it-look-good payload. */
export const FINISHING: Item[] = [
  {
    id: "marcona-almond",
    name: "Marcona almonds",
    cat: "nut",
    palette: ["#e2c48a", "#cfae6e", "#f2e0b4"],
    motif: "scatter",
    tags: ["nutty", "salty", "buttery", "crunchy", "rich"],
    note: "Fried in oil and salted. Rounder, softer and better than regular almonds.",
    loves: ["manchego", "chorizo", "date", "membrillo", "jamon-iberico"],
    cuts: [
      {
        name: "Small Bowl",
        how: "They're oily — keep them in a small bowl or they'll grease everything they touch.",
        motif: "bowl",
        effort: 1,
      },
      {
        name: "Gap Filler",
        how: "Spoon into the awkward triangles between round things. Nuts exist to fill geometry.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "pecan",
    name: "Candied pecans",
    cat: "nut",
    palette: ["#a06a3c", "#84532c", "#d09a5e"],
    motif: "scatter",
    tags: ["sweet", "nutty", "crunchy", "rich", "smoky"],
    note: "Toast with maple, salt and a pinch of cayenne. Five minutes, huge payoff.",
    loves: ["roquefort", "smoked-gouda", "pear", "dried-cherry"],
    cuts: [
      {
        name: "Clustered Rubble",
        how: "Let them clump — candied nuts that stick together in shards look better than separated ones.",
        motif: "scatter",
        effort: 2,
      },
    ],
  },
  {
    id: "walnut",
    name: "Walnut halves",
    cat: "nut",
    palette: ["#b08a5e", "#956f46", "#d8bc90"],
    motif: "scatter",
    tags: ["nutty", "bitter", "crunchy", "earthy", "rich"],
    note: "Toast them. Raw walnuts are bitter and nobody eats them.",
    loves: ["roquefort", "stilton", "pear", "fig", "comte", "honeycomb"],
    cuts: [
      {
        name: "Intact Halves",
        how: "Use whole halves, not pieces — that brain-like surface is a texture nothing else provides.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "pistachio",
    name: "Pistachios",
    cat: "nut",
    palette: ["#8fa04c", "#75873a", "#c4cf82"],
    motif: "scatter",
    tags: ["nutty", "salty", "crunchy", "grassy", "light"],
    note: "The only green nut. Shelled in a bowl, or in-shell as a whole activity.",
    loves: ["mortadella", "ricotta", "dried-apricot", "citrus", "honeycomb"],
    cuts: [
      {
        name: "Shelled Drift",
        how: "Shell them ahead. In-shell nuts are a project, not a snack.",
        motif: "scatter",
        effort: 2,
      },
      {
        name: "Crushed Dust",
        how: "Crush and scatter over soft cheeses and honey as a finishing texture.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "hazelnut",
    name: "Hazelnuts",
    cat: "nut",
    palette: ["#a06f42", "#84582f", "#cf9e68"],
    motif: "scatter",
    tags: ["nutty", "crunchy", "earthy", "rich", "smoky"],
    note: "Toast and rub the skins off in a tea towel. Worth the mess.",
    loves: ["dark-chocolate", "comte", "pear", "gruyere"],
    cuts: [
      {
        name: "Toasted Whole",
        how: "Whole and toasted, piled where they'll catch the light off their oil.",
        motif: "scatter",
        effort: 2,
      },
    ],
  },
  {
    id: "smoked-almond",
    name: "Smoked almonds",
    cat: "nut",
    palette: ["#8a6242", "#6e4c30", "#b58a62"],
    motif: "scatter",
    tags: ["smoky", "salty", "crunchy", "nutty", "bold"],
    note: "The savoury nut. Balances a board that's drifting sweet.",
    loves: ["cheddar", "smoked-gouda", "mustard"],
    cuts: [
      {
        name: "Loose Handful",
        how: "Scatter directly on the wood in a loose river between two cheeses.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "cashew",
    name: "Cashews",
    cat: "nut",
    palette: ["#e0c496", "#cbab78", "#f2e2c0"],
    motif: "scatter",
    tags: ["nutty", "buttery", "crunchy", "mild", "sweet"],
    note: "Mild and creamy — the nut for people who claim not to like nuts.",
    loves: ["dried-mango", "havarti", "honeycomb"],
    cuts: [
      {
        name: "Curved Rows",
        how: "Their crescent shape nests — lay them following the curve of a nearby blob.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "dark-chocolate",
    name: "Dark chocolate",
    cat: "sweet",
    palette: ["#4a2f26", "#36211a", "#7a5442"],
    motif: "cube",
    tags: ["bitter", "sweet", "rich", "firm", "bold"],
    note: "70% or higher, broken not cut. The board's full stop.",
    loves: ["aged-gouda", "dried-cherry", "hazelnut", "strawberry", "candied-orange"],
    cuts: [
      {
        name: "Snapped Shards",
        how: "Snap the bar by hand into irregular pieces. A neat row of squares looks like a vending machine.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "choc-almond",
    name: "Chocolate-covered almonds",
    cat: "sweet",
    palette: ["#5e3f30", "#472e22", "#8a6450"],
    motif: "scatter",
    tags: ["sweet", "nutty", "crunchy", "rich", "bitter"],
    note: "Dark and glossy. They roll into gaps and look deliberate.",
    loves: ["dark-chocolate", "dried-cherry", "aged-gouda"],
    cuts: [
      {
        name: "Rolled Into Gaps",
        how: "Drop a handful and let them settle wherever they land. This is the one time random is right.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "amaretti",
    name: "Amaretti",
    cat: "sweet",
    palette: ["#e8d2a2", "#d4ba84", "#f4e8cc"],
    motif: "round",
    tags: ["sweet", "nutty", "crunchy", "floral", "light"],
    note: "Crisp almond biscuits in crinkly paper. Leave some wrapped.",
    loves: ["triple-creme", "citrus", "dark-chocolate"],
    cuts: [
      {
        name: "Half-Wrapped",
        how: "Leave a few in their twisted paper wrappers among the unwrapped ones.",
        motif: "round",
        effort: 1,
      },
    ],
  },
  {
    id: "shortbread",
    name: "Shortbread",
    cat: "sweet",
    palette: ["#f0dcae", "#dcc48e", "#f8eed4"],
    motif: "batons",
    tags: ["buttery", "sweet", "crumbly", "rich", "mild"],
    note: "Pure butter. Surprisingly good against a sharp blue.",
    loves: ["stilton", "roquefort", "citrus"],
    cuts: [
      {
        name: "Stacked Fingers",
        how: "Stack in a log-cabin square, two by two, so it stands off the board.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "rosemary",
    name: "Rosemary sprigs",
    cat: "garnish",
    palette: ["#5e7d4c", "#46603a", "#8fa86e"],
    motif: "sprig",
    tags: ["herbal", "earthy", "bitter", "grassy", "bold"],
    note: "Structural, evergreen, smells like the whole board looks.",
    loves: ["crostini", "manchego", "honeycomb", "walnut"],
    cuts: [
      {
        name: "Tucked Into Seams",
        how: "Push short sprigs into the gaps between piles, at angles, so they look like they grew there.",
        motif: "sprig",
        flair: "Garnish goes in last and in the negative space. Never on top of food.",
        effort: 1,
      },
    ],
  },
  {
    id: "thyme",
    name: "Thyme",
    cat: "garnish",
    palette: ["#6e8a54", "#546e40", "#9ab078"],
    motif: "sprig",
    tags: ["herbal", "floral", "earthy", "light", "grassy"],
    note: "Small, fine, delicate. Scatter loose leaves over soft cheese.",
    loves: ["chevre", "honeycomb", "blackberry", "brie"],
    cuts: [
      {
        name: "Loose Sprigs",
        how: "Lay whole sprigs across a cheese and strip a few leaves over the honey.",
        motif: "sprig",
        effort: 1,
      },
    ],
  },
  {
    id: "basil",
    name: "Fresh basil",
    cat: "garnish",
    palette: ["#4a8a44", "#367034", "#7ab070"],
    motif: "sprig",
    tags: ["herbal", "floral", "grassy", "light", "peppery"],
    note: "Tear it, don't cut it — a blade bruises the leaf black.",
    loves: ["burrata", "peach", "mozzarella", "olive-oil"],
    cuts: [
      {
        name: "Torn Leaves",
        how: "Tear the leaves by hand and drop them from a height so they land irregularly.",
        motif: "sprig",
        effort: 1,
      },
    ],
  },
  {
    id: "mint",
    name: "Mint",
    cat: "garnish",
    palette: ["#5aa05e", "#428446", "#8ec48e"],
    motif: "sprig",
    tags: ["herbal", "light", "grassy", "floral", "acidic"],
    note: "Cuts through fat and makes melon taste more like melon.",
    loves: ["melon", "feta", "pomegranate", "citrus", "halloumi"],
    cuts: [
      {
        name: "Whole Tips",
        how: "Use the top three leaves of each stem — the small ones look intentional, big ones look like salad.",
        motif: "sprig",
        effort: 1,
      },
    ],
  },
  {
    id: "edible-flowers",
    name: "Edible flowers",
    cat: "garnish",
    palette: ["#d97a9a", "#c25a7e", "#f0b4c4"],
    motif: "sprig",
    tags: ["floral", "light", "mild", "grassy", "bitter"],
    note: "Nasturtium, viola, borage. Ridiculous, and it works every time.",
    loves: ["chevre", "ricotta", "honeycomb", "strawberry"],
    cuts: [
      {
        name: "Scattered Last",
        how: "Place them individually with tweezers or damp fingers, after everything else is done.",
        motif: "sprig",
        flair: "Three flowers reads as styled. Thirty reads as a hedge.",
        effort: 2,
      },
    ],
  },
  {
    id: "sage",
    name: "Fried sage",
    cat: "garnish",
    palette: ["#8a9a7a", "#6e7d60", "#b4c0a4"],
    motif: "sprig",
    tags: ["herbal", "earthy", "crunchy", "bitter", "rich"],
    note: "Twenty seconds in hot butter turns sage into a translucent crisp.",
    loves: ["taleggio", "walnut", "pate", "honeycomb"],
    cuts: [
      {
        name: "Crisped Whole",
        how: "Fry whole leaves in butter until they stop bubbling, drain on paper, salt immediately.",
        motif: "sprig",
        effort: 3,
      },
    ],
  },
  {
    id: "microgreens",
    name: "Microgreens",
    cat: "garnish",
    palette: ["#7aa84c", "#5e8a36", "#a8c47e"],
    motif: "sprig",
    tags: ["grassy", "light", "peppery", "herbal", "bitter"],
    note: "A pinch of green where nothing else fits. Pea shoots are the prettiest.",
    loves: ["burrata", "bresaola", "chevre", "olive-oil"],
    cuts: [
      {
        name: "Pinched Tufts",
        how: "Small tufts pinched into seams, all leaning the same direction.",
        motif: "sprig",
        effort: 1,
      },
    ],
  },

  // ─── Added in the expansion ────────────────────────────────────────────────
  {
    id: "pine-nut",
    name: "Toasted pine nuts",
    cat: "nut",
    palette: ["#e2cf9e", "#cbb47e", "#f2e6c8"],
    motif: "scatter",
    tags: ["nutty", "buttery", "rich", "mild", "crunchy"],
    note: "Toast them and they turn resinous and sweet. Burn them in about nine seconds.",
    loves: ["ricotta", "golden-raisin", "basil", "pecorino"],
    cuts: [
      {
        name: "Scattered Over Soft Cheese",
        how: "Toast in a dry pan, shaking constantly, then scatter over anything creamy while still warm.",
        motif: "scatter",
        effort: 2,
      },
    ],
  },
  {
    id: "macadamia",
    name: "Macadamias",
    cat: "nut",
    palette: ["#f2e4c8", "#dfceac", "#fbf4e4"],
    motif: "scatter",
    tags: ["buttery", "rich", "crunchy", "mild", "sweet"],
    note: "Pale, round and absurdly buttery. The most expensive thing in the nut aisle.",
    loves: ["brie", "dark-chocolate", "dried-pineapple", "honeycomb"],
    cuts: [
      {
        name: "Whole & Salted",
        how: "Whole, lightly salted, in a small pile. Halving them wastes the shape.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "chestnut",
    name: "Roasted chestnuts",
    cat: "nut",
    palette: ["#a06a42", "#84512c", "#e0c49e"],
    season: [11, 12, 1],
    motif: "cluster",
    tags: ["sweet", "earthy", "nutty", "chewy", "rich"],
    note: "Vacuum-packed is fine and saves an hour of peeling. Warm them through.",
    loves: ["stilton", "comte", "onion-jam", "speck"],
    cuts: [
      {
        name: "Warm & Broken",
        how: "Warm them and break each one roughly in half so the crumbly interior shows.",
        motif: "cluster",
        effort: 2,
      },
    ],
  },
  {
    id: "brazil-nut",
    name: "Brazil nuts",
    cat: "nut",
    palette: ["#c4a878", "#a88e5e", "#e4d4b4"],
    motif: "scatter",
    tags: ["nutty", "rich", "crunchy", "earthy", "bold"],
    note: "Big, dense, slightly waxy. Shave them and they behave much better.",
    loves: ["dark-chocolate", "date", "aged-gouda"],
    cuts: [
      {
        name: "Shaved into Curls",
        how: "Run a peeler down the side of each nut for pale curls that scatter like coconut.",
        motif: "scatter",
        flair: "Nobody expects a shaved nut. It looks like something else entirely.",
        effort: 2,
      },
    ],
  },
  {
    id: "biscotti",
    name: "Biscotti",
    cat: "sweet",
    palette: ["#e2c496", "#cbaa76", "#8a6242"],
    motif: "batons",
    tags: ["sweet", "nutty", "crunchy", "buttery", "firm"],
    note: "Twice-baked and properly hard. Meant for dunking, not biting.",
    loves: ["mascarpone", "dark-chocolate", "dried-cherry", "citrus"],
    cuts: [
      {
        name: "Standing in a Jar",
        how: "Stand them upright in a short jar at the board's edge for instant height.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "halva",
    name: "Halva",
    cat: "sweet",
    palette: ["#e0c894", "#c9ac72", "#8a6a44"],
    motif: "crumble",
    tags: ["sweet", "nutty", "crumbly", "rich", "earthy"],
    note: "Sesame paste and sugar, flaky and dense. Marbled with chocolate if you're lucky.",
    loves: ["labneh", "dark-chocolate", "clementine", "pistachio"],
    cuts: [
      {
        name: "Broken Slabs",
        how: "Break it along the grain into rough slabs so the flaky striations show.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "turkish-delight",
    name: "Turkish delight",
    cat: "sweet",
    palette: ["#d95a7c", "#bd4462", "#f2e2d4"],
    motif: "cube",
    tags: ["sweet", "floral", "chewy", "light", "bold"],
    note: "Rose or pistachio, buried in icing sugar. Jewel-coloured and very pretty.",
    loves: ["dark-chocolate", "pistachio", "labneh", "mint"],
    cuts: [
      {
        name: "Dusted Cubes",
        how: "Leave the icing sugar on and stack the cubes loosely so the dust scatters.",
        motif: "cube",
        effort: 1,
      },
    ],
  },
  {
    id: "marzipan",
    name: "Marzipan",
    cat: "sweet",
    palette: ["#f2e4c0", "#dfcd9e", "#c9a86e"],
    motif: "cube",
    tags: ["sweet", "nutty", "chewy", "floral", "rich"],
    note: "Almond paste, dense and perfumed. Divisive, and the people who like it really like it.",
    loves: ["dark-chocolate", "clementine", "dried-cherry", "biscotti"],
    cuts: [
      {
        name: "Thin Batons",
        how: "Cut into small batons — a big piece is overwhelming.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "chocolate-truffle",
    name: "Chocolate truffles",
    cat: "sweet",
    palette: ["#4a2f26", "#36211a", "#8a6a54"],
    motif: "cluster",
    tags: ["bitter", "sweet", "rich", "creamy", "bold"],
    note: "Cocoa-dusted, matte and dark. The full stop, in spherical form.",
    loves: ["raspberry", "dried-cherry", "mascarpone", "hazelnut"],
    cuts: [
      {
        name: "Loose Cluster",
        how: "Pile them in odd numbers in a small dish. They roll, so give them walls.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "dill",
    name: "Dill",
    cat: "garnish",
    palette: ["#6e9a54", "#548040", "#a8c488"],
    motif: "sprig",
    tags: ["herbal", "grassy", "light", "acidic", "floral"],
    note: "Feathery and sharp. Belongs anywhere there's smoked fish or pickles.",
    loves: ["smoked-salmon", "cream-cheese", "cucumber", "pickled-onion", "labneh"],
    cuts: [
      {
        name: "Feathered Fronds",
        how: "Pull it into small feathery pieces and drop them from a height so they land irregularly.",
        motif: "sprig",
        effort: 1,
      },
    ],
  },
  {
    id: "chive",
    name: "Chives",
    cat: "garnish",
    palette: ["#5a8a4a", "#427036", "#8fb478"],
    motif: "batons",
    tags: ["herbal", "garlicky", "grassy", "light", "peppery"],
    note: "Straight green lines — the only truly geometric garnish available.",
    loves: ["cream-cheese", "labneh", "smoked-salmon", "boursin"],
    cuts: [
      {
        name: "Long Batons",
        how: "Leave them long and lay them in a crossed pile rather than snipping them into confetti.",
        motif: "batons",
        flair: "Long chives read as deliberate; snipped ones read as leftovers.",
        effort: 1,
      },
    ],
  },
  {
    id: "tarragon",
    name: "Tarragon",
    cat: "garnish",
    palette: ["#6e8a4c", "#547038", "#9ab478"],
    motif: "sprig",
    tags: ["herbal", "floral", "bitter", "light", "grassy"],
    note: "Faintly aniseed. Surprising next to a soft goat cheese.",
    loves: ["chevre", "ricotta", "prosciutto-cotto", "labneh"],
    cuts: [
      {
        name: "Whole Tips",
        how: "Use the top few leaves of each stem and lay them whole.",
        motif: "sprig",
        effort: 1,
      },
    ],
  },
  {
    id: "pink-peppercorn",
    name: "Pink peppercorns",
    cat: "garnish",
    palette: ["#e07a8a", "#c25a6e", "#f2b4bc"],
    motif: "scatter",
    tags: ["peppery", "floral", "light", "spicy", "bold"],
    perGuest: { amount: 1, unit: "pinch" },
    note: "Not really pepper. Fruity, faintly resinous, and an improbable pink.",
    loves: ["chevre", "smoked-salmon", "burrata", "strawberry"],
    cuts: [
      {
        name: "Crushed Between Fingers",
        how: "Crush them as you scatter so they break into pink flecks rather than sitting as whole balls.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "flaky-salt",
    name: "Flaky sea salt",
    cat: "garnish",
    palette: ["#fbfaf6", "#e8e6de", "#ffffff"],
    motif: "scatter",
    perGuest: { amount: 1, unit: "pinch" },
    tags: ["salty", "crunchy", "mild", "light", "bold"],
    note: "Maldon or similar. The single cheapest upgrade to anything on the board.",
    loves: ["burrata", "olive-oil", "radish", "dark-chocolate", "foie-gras"],
    cuts: [
      {
        name: "Pinched from Height",
        how: "Pinch and scatter from about a foot up so it lands evenly rather than in a clump.",
        motif: "scatter",
        flair: "Put the rest out in a tiny open dish. People will use it.",
        effort: 1,
      },
    ],
  },
  {
    id: "fennel-frond",
    name: "Fennel fronds",
    cat: "garnish",
    palette: ["#7aa04c", "#5e8436", "#b4c884"],
    motif: "sprig",
    tags: ["herbal", "floral", "grassy", "light", "bitter"],
    note: "Wispy and faintly aniseed. Free if you buy the bulb.",
    loves: ["finocchiona", "smoked-salmon", "olive-oil", "cucumber"],
    cuts: [
      {
        name: "Wispy Tufts",
        how: "Tuck small tufts into the seams so they look like they're growing out of the board.",
        motif: "sprig",
        effort: 1,
      },
    ],
  },
];
