import type { Item } from "../types";

/** Cured meat and pâté. Palettes are [base, mid, accent] and feed the motif
 *  generators; `cuts` is the how-to-make-it-look-good payload. */
export const MEATS: Item[] = [
  {
    id: "prosciutto",
    name: "Prosciutto di Parma",
    cat: "meat",
    palette: ["#e8a5a0", "#d9848a", "#f6dcd6"],
    motif: "drape",
    tags: ["salty", "silky", "umami", "rich", "bold"],
    note: "Sliced so thin it's translucent. Ask them not to stack the sheets.",
    loves: ["melon", "fig", "peach", "burrata", "parmigiano", "grissini"],
    cuts: [
      {
        name: "The Ruffle",
        how: "Pinch each slice at the centre and let the edges fall into loose folds. Never lay it flat — flat prosciutto looks like lunch meat.",
        motif: "ruffle",
        flair: "Air is the ingredient. Aim for more air than meat.",
        effort: 2,
      },
      {
        name: "Grissini Wraps",
        how: "Spiral a half-slice down each breadstick, leaving gaps so the stick shows through. Stand them in a jar.",
        motif: "batons",
        effort: 2,
      },
      {
        name: "Melon Saddles",
        how: "Drape a half-slice over each melon wedge so it slumps down both sides.",
        motif: "drape",
        effort: 1,
      },
    ],
  },
  {
    id: "soppressata",
    name: "Soppressata",
    cat: "meat",
    palette: ["#c05d5a", "#a8474a", "#f0e0d2"],
    motif: "rose",
    tags: ["salty", "spicy", "chewy", "bold", "umami"],
    note: "Coarse-ground, pressed flat, properly spicy. The rose-making salami.",
    loves: ["pepper-jelly", "castelvetrano", "grissini"],
    cuts: [
      {
        name: "Salami Rose",
        how: "Drape slices over the rim of a wine glass, overlapping halfway, all the way around. Add a second layer inside. Invert onto the board and lift the glass away.",
        motif: "rose",
        flair: "The single highest ratio of gasps to effort in all of food.",
        effort: 2,
      },
      {
        name: "Salami River",
        how: "Fold each slice in quarters into a fan, then shingle the fans in a meandering line across the board.",
        motif: "shingle",
        effort: 1,
      },
      {
        name: "Coin Scatter",
        how: "Lay slices flat in overlapping runs of three, angled differently each run.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "genoa",
    name: "Genoa salami",
    cat: "meat",
    palette: ["#cf7371", "#b85a5c", "#f2e6d8"],
    motif: "shingle",
    tags: ["salty", "garlicky", "chewy", "mild", "umami"],
    note: "Soft, wine-cured, marbled with fat. The everyday salami.",
    loves: ["peperoncini", "grissini", "mustard"],
    cuts: [
      {
        name: "Quarter Folds",
        how: "Fold each slice in half, then half again, and stand the fans up in a row like a deck of cards mid-shuffle.",
        motif: "shingle",
        effort: 1,
      },
      {
        name: "Salami Rose",
        how: "Wine-glass method: overlap slices around the rim, invert, lift.",
        motif: "rose",
        effort: 2,
      },
    ],
  },
  {
    id: "finocchiona",
    name: "Finocchiona",
    cat: "meat",
    palette: ["#c96f68", "#b25a55", "#e8dcc4"],
    motif: "shingle",
    tags: ["salty", "herbal", "chewy", "umami", "bold"],
    note: "Tuscan salami shot through with fennel seed. Sweet and aniseedy.",
    loves: ["pecorino", "castelvetrano", "olive-oil", "sourdough"],
    cuts: [
      {
        name: "Flat Overlap",
        how: "Lay it flat and overlapping — the fennel seeds are the pattern, don't hide them in a fold.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "chorizo",
    name: "Spanish chorizo",
    cat: "meat",
    palette: ["#b4463a", "#98342c", "#e0723f"],
    motif: "shingle",
    tags: ["smoky", "spicy", "salty", "firm", "bold"],
    note: "Cured, not fresh. Smoked paprika does all the heavy lifting.",
    loves: ["manchego", "castelvetrano", "marcona-almond", "membrillo"],
    cuts: [
      {
        name: "Salami Rose",
        how: "Drape slices over the rim of a wine glass, overlapping halfway round, four or five deep. Press a saucer on top, invert onto the board and lift the glass away — the slices fall open into petals.",
        motif: "rose",
        flair: "The one thing on a board people always ask about. It takes ninety seconds.",
        effort: 2,
      },
      {
        name: "Bias Coins",
        how: "Slice hard on the diagonal for long ovals rather than small circles — more surface, more colour.",
        motif: "shingle",
        effort: 1,
      },
      {
        name: "Crisped Cups",
        how: "Pan-fry the coins 60 seconds a side; they curl into little cups. Serve warm, in a bowl, with the paprika oil.",
        motif: "cluster",
        effort: 2,
      },
    ],
  },
  {
    id: "nduja",
    name: "'Nduja",
    cat: "meat",
    palette: ["#b83e2e", "#9c2f22", "#d75a34"],
    motif: "bowl",
    tags: ["spicy", "spreadable", "smoky", "rich", "bold"],
    note: "Spreadable Calabrian salami. Fiery, fatty, unforgettable.",
    loves: ["ricotta", "honeycomb", "sourdough", "burrata"],
    cuts: [
      {
        name: "Warm Puddle",
        how: "Spoon into a small bowl and warm it slightly so it loosens into a glossy, spoonable puddle.",
        motif: "bowl",
        flair: "Swirl it into whipped ricotta and watch the board disappear.",
        effort: 2,
      },
    ],
  },
  {
    id: "coppa",
    name: "Coppa",
    cat: "meat",
    palette: ["#cf6f6a", "#b2534f", "#f4e2d4"],
    motif: "drape",
    tags: ["salty", "silky", "peppery", "rich", "umami"],
    note: "Cured pork neck — the marbling is the whole point.",
    loves: ["fig", "grissini", "pecorino", "peach"],
    cuts: [
      {
        name: "Loose Ribbons",
        how: "Slice thin and lay in loose S-curves so the marbling reads as a pattern.",
        motif: "drape",
        effort: 1,
      },
    ],
  },
  {
    id: "bresaola",
    name: "Bresaola",
    cat: "meat",
    palette: ["#8e3b3f", "#752f34", "#c8807c"],
    motif: "drape",
    tags: ["salty", "light", "umami", "silky", "mild"],
    note: "Air-dried beef, deep garnet, almost no fat. The lean one.",
    loves: ["parmigiano", "olive-oil", "caper-berry", "microgreens"],
    cuts: [
      {
        name: "Carpaccio Rosettes",
        how: "Lay slices flat, dress with oil and lemon, shave Parmesan over, then roll each into a loose rosette.",
        motif: "rose",
        effort: 2,
      },
    ],
  },
  {
    id: "mortadella",
    name: "Mortadella",
    cat: "meat",
    palette: ["#f0c2bd", "#e2a6a2", "#8fa05c"],
    motif: "drape",
    tags: ["mild", "silky", "rich", "salty", "nutty"],
    note: "The pink one with pistachios. Underrated by people who fear bologna.",
    loves: ["pistachio", "grissini", "ricotta", "mozzarella"],
    cuts: [
      {
        name: "Cloud Folds",
        how: "Slice paper-thin and gather each sheet loosely into a puff. It should look like a pink cloud, not a slice.",
        motif: "drape",
        flair: "Pistachio dust over the top ties it back to the studs inside.",
        effort: 2,
      },
      {
        name: "Thick Cubes",
        how: "Cut a half-inch slab into cubes and spear each with a pick. Very Bologna, very correct.",
        motif: "cube",
        effort: 1,
      },
    ],
  },
  {
    id: "speck",
    name: "Speck",
    cat: "meat",
    palette: ["#c4645e", "#a84c48", "#eddcc8"],
    motif: "drape",
    tags: ["smoky", "salty", "silky", "umami", "bold"],
    note: "Alpine prosciutto that's been smoked. Juniper, pine, woodsmoke.",
    loves: ["gruyere", "pear", "cornichon"],
    cuts: [
      {
        name: "Torn Ribbons",
        how: "Tear rather than cut — the ragged edge reads as rustic and catches light.",
        motif: "drape",
        effort: 1,
      },
    ],
  },
  {
    id: "jamon-iberico",
    name: "Jamón ibérico",
    cat: "meat",
    palette: ["#c25f5c", "#a3453f", "#efdcc2"],
    motif: "drape",
    tags: ["salty", "nutty", "umami", "rich", "bold"],
    note: "Acorn-fed, aged for years. The fat melts at room temperature.",
    loves: ["manchego", "marcona-almond", "castelvetrano", "membrillo"],
    cuts: [
      {
        name: "Single Layer, No Touching",
        how: "Lay each slice flat and separate on a warm plate. It's too expensive to hide under anything.",
        motif: "drape",
        flair: "Warm the plate. The fat should just start to gloss.",
        effort: 1,
      },
    ],
  },
  {
    id: "pate",
    name: "Pâté de campagne",
    cat: "meat",
    palette: ["#c9a184", "#b08668", "#6d4a33"],
    motif: "cube",
    tags: ["rich", "earthy", "spreadable", "umami", "bold"],
    note: "Coarse country pâté. Rustic, peppery, made for cornichons.",
    loves: ["cornichon", "mustard", "baguette", "onion-jam"],
    cuts: [
      {
        name: "Thick Slabs",
        how: "Cut cold into thick slabs and lay them slightly overlapping with cornichons wedged between.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "rillettes",
    name: "Duck rillettes",
    cat: "meat",
    palette: ["#dcbc95", "#c6a077", "#8a6544"],
    motif: "bowl",
    tags: ["rich", "salty", "spreadable", "umami", "silky"],
    note: "Slow-cooked duck shredded into its own fat. Absurdly good.",
    loves: ["cornichon", "baguette", "mustard", "onion-jam"],
    cuts: [
      {
        name: "Crock & Fork",
        how: "Serve in a small crock with the fat cap intact, and a fork to break through it.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },

  // ─── Added in the expansion ────────────────────────────────────────────────
  {
    id: "saucisson-sec",
    name: "Saucisson sec",
    cat: "meat",
    palette: ["#c46a63", "#a8514d", "#f2e4d6"],
    motif: "shingle",
    tags: ["salty", "chewy", "garlicky", "umami", "bold"],
    note: "French dry sausage with a bloomy white rind. Buy the whole baton.",
    loves: ["cornichon", "baguette", "comte", "mustard"],
    cuts: [
      {
        name: "Whole Baton & Knife",
        how: "Put the whole sausage out with a small knife and let people cut their own. Slice a dozen coins to start them off.",
        motif: "shingle",
        flair: "The uncut baton signals abundance better than any arrangement.",
        effort: 1,
      },
    ],
  },
  {
    id: "salchichon",
    name: "Salchichón",
    cat: "meat",
    palette: ["#c26660", "#a64c4a", "#efe0d0"],
    motif: "shingle",
    tags: ["salty", "peppery", "chewy", "umami", "mild"],
    note: "Spanish peppercorn salami. Less paprika than chorizo, more black pepper.",
    loves: ["manchego", "castelvetrano", "membrillo", "lavash"],
    cuts: [
      {
        name: "Paper Coins",
        how: "Slice as thin as you can manage and lay them in a loose overlapping spiral.",
        motif: "shingle",
        effort: 2,
      },
    ],
  },
  {
    id: "lomo",
    name: "Lomo embuchado",
    cat: "meat",
    palette: ["#a8453f", "#8a3430", "#e0a08a"],
    motif: "drape",
    tags: ["salty", "smoky", "silky", "umami", "rich"],
    note: "Cured pork loin, deep red, paprika-rubbed. Lean and intense.",
    loves: ["manchego", "marcona-almond", "membrillo", "olive-oil"],
    cuts: [
      {
        name: "Translucent Sheets",
        how: "Slice thin enough to see light through, and lay flat and separate — it's too good to fold.",
        motif: "drape",
        effort: 2,
      },
    ],
  },
  {
    id: "culatello",
    name: "Culatello",
    cat: "meat",
    palette: ["#e09a95", "#cf7a7e", "#f7e2da"],
    motif: "drape",
    tags: ["salty", "silky", "floral", "umami", "rich"],
    note: "The heart of the prosciutto, aged in river fog. Absurdly expensive, worth it.",
    loves: ["parmigiano", "grissini", "fig", "melon"],
    cuts: [
      {
        name: "Loose Sheets",
        how: "One layer, barely touching, at room temperature. Do not stack it and do not hide it.",
        motif: "drape",
        effort: 1,
      },
    ],
  },
  {
    id: "lardo",
    name: "Lardo",
    cat: "meat",
    palette: ["#fbf4ec", "#efe4d6", "#d99a94"],
    motif: "drape",
    tags: ["salty", "silky", "herbal", "rich", "bold"],
    note: "Cured back fat with rosemary. It melts on your hand. Deeply unfashionable and delicious.",
    loves: ["sourdough", "rosemary", "honeycomb", "crostini"],
    cuts: [
      {
        name: "Draped on Warm Toast",
        how: "Shave paper-thin and lay over toast straight from the grill so it goes translucent as it melts.",
        motif: "drape",
        flair: "Serve it the moment it turns glassy. That window is about a minute.",
        effort: 2,
      },
    ],
  },
  {
    id: "jamon-serrano",
    name: "Jamón serrano",
    cat: "meat",
    palette: ["#c96f68", "#ad524d", "#f2e0cc"],
    motif: "drape",
    tags: ["salty", "chewy", "umami", "mild", "bold"],
    note: "The everyday Spanish ham. Firmer and far cheaper than ibérico.",
    loves: ["manchego", "melon", "castelvetrano", "grissini"],
    cuts: [
      {
        name: "Rumpled Piles",
        how: "Gather slices into loose rumpled heaps rather than laying them flat.",
        motif: "drape",
        effort: 1,
      },
    ],
  },
  {
    id: "prosciutto-cotto",
    name: "Prosciutto cotto",
    cat: "meat",
    palette: ["#f2c4bc", "#e2a49e", "#f7ead8"],
    motif: "drape",
    tags: ["mild", "silky", "salty", "light", "buttery"],
    note: "Cooked ham, delicately herbed. The gentle option on a board of intense things.",
    loves: ["havarti", "grissini", "mustard", "melon"],
    cuts: [
      {
        name: "Folded Ribbons",
        how: "Fold each slice into a loose ribbon and stand them up in a row.",
        motif: "drape",
        effort: 1,
      },
    ],
  },
  {
    id: "truffle-salami",
    name: "Truffle salami",
    cat: "meat",
    palette: ["#c46e6a", "#a8504e", "#5e4a44"],
    motif: "shingle",
    tags: ["earthy", "salty", "umami", "rich", "bold"],
    note: "Salami shot through with black truffle. Smells like a wine cellar.",
    loves: ["taleggio", "honeycomb", "crostini", "parmigiano"],
    cuts: [
      {
        name: "Fanned Coins",
        how: "Thin coins fanned in a curve so the truffle flecks read as a pattern.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "landjaeger",
    name: "Landjäger",
    cat: "meat",
    palette: ["#8a4a38", "#6e3628", "#c98a6e"],
    motif: "batons",
    tags: ["smoky", "salty", "chewy", "umami", "bold"],
    note: "Flat smoked hiking sausage. Snappy, portable, faintly campfire.",
    loves: ["mustard", "cornichon", "gruyere", "rye-crisp"],
    cuts: [
      {
        name: "Split Lengthways",
        how: "Halve each one lengthways and lay them cut-side up, crossed in a stack.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "biltong",
    name: "Biltong",
    cat: "meat",
    palette: ["#7a3a2e", "#5e2a20", "#b07a62"],
    motif: "scatter",
    tags: ["salty", "chewy", "spicy", "umami", "bold"],
    note: "Coriander-cured air-dried beef. Not jerky — no sugar, no smoke.",
    loves: ["cheddar", "mustard", "pickled-onion", "smoked-almond"],
    cuts: [
      {
        name: "Thick Slices",
        how: "Slice across the grain into fat pieces so it stays tender rather than stringy.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "duck-prosciutto",
    name: "Duck prosciutto",
    cat: "meat",
    palette: ["#9e3f42", "#802f34", "#e8c0a8"],
    motif: "drape",
    tags: ["salty", "rich", "silky", "umami", "bold"],
    note: "Cured duck breast with a thick cap of fat. Dark, dense, luxurious.",
    loves: ["fig", "pear", "honeycomb", "pistachio"],
    cuts: [
      {
        name: "Fat-Cap Slices",
        how: "Slice thin through breast and fat together so every piece carries its white edge.",
        motif: "drape",
        effort: 2,
      },
    ],
  },
  {
    id: "foie-gras",
    name: "Foie gras terrine",
    cat: "meat",
    palette: ["#f2d9a8", "#e2c184", "#c99a5e"],
    motif: "cube",
    tags: ["rich", "buttery", "silky", "umami", "bold"],
    note: "The most decadent thing you can put on a board. A little goes a long way.",
    loves: ["brioche-toast", "fig-jam", "date", "apricot-preserve"],
    cuts: [
      {
        name: "Warm-Knife Slabs",
        how: "Dip the knife in hot water between cuts for clean slabs, and serve with flaky salt on top.",
        motif: "cube",
        flair: "Toast the brioche to order. Cold toast wastes the whole exercise.",
        effort: 3,
      },
    ],
  },
  {
    id: "smoked-salmon",
    name: "Smoked salmon",
    cat: "meat",
    palette: ["#f0906e", "#dc7050", "#fbd9c4"],
    motif: "drape",
    tags: ["smoky", "salty", "silky", "umami", "rich"],
    note: "Cold-smoked, sliced thin. The brunch board's anchor.",
    loves: ["cream-cheese", "dill", "pickled-onion", "rye-crisp", "labneh"],
    cuts: [
      {
        name: "Loose Roses",
        how: "Roll each slice loosely from one end into a rose and stand them cut-side up.",
        motif: "rose",
        effort: 2,
      },
    ],
  },
];
