import type { Item } from "../types";

/** Crackers, bread, spreads, pickles. Palettes are [base, mid, accent] and feed the motif
 *  generators; `cuts` is the how-to-make-it-look-good payload. */
export const PANTRY: Item[] = [
  {
    id: "water-cracker",
    name: "Water crackers",
    cat: "cracker",
    palette: ["#f0e4c8", "#e0d0aa", "#faf2de"],
    motif: "fan",
    tags: ["crunchy", "mild", "light", "flaky", "firm"],
    note: "Deliberately boring so the cheese does the talking. Essential.",
    loves: ["brie", "triple-creme", "boursin", "gorgonzola-dolce"],
    cuts: [
      {
        name: "Toppled Stack",
        how: "Stack them, then push the stack over so they cascade in a curve like a fallen domino run.",
        motif: "fan",
        flair: "A toppled stack reads as abundance. A neat stack reads as a waiting room.",
        effort: 1,
      },
      {
        name: "Standing Rows",
        how: "Wedge them upright between two cheeses so they stand on edge in a fan.",
        motif: "stack",
        effort: 2,
      },
    ],
  },
  {
    id: "seeded-crisp",
    name: "Seeded crisps",
    cat: "cracker",
    palette: ["#d9c096", "#c2a67a", "#6e5a3c"],
    motif: "fan",
    tags: ["crunchy", "nutty", "earthy", "firm", "bold"],
    note: "Loaded with seeds and grain. Sturdy enough for a heavy spread.",
    loves: ["chevre", "hummus", "roquefort", "onion-jam"],
    cuts: [
      {
        name: "Angled Cascade",
        how: "Lay them in a long overlapping run at a consistent angle so the seeds create a repeating texture.",
        motif: "fan",
        effort: 1,
      },
    ],
  },
  {
    id: "crostini",
    name: "Rosemary crostini",
    cat: "cracker",
    palette: ["#dcb87e", "#c49e62", "#7d8f4a"],
    motif: "round",
    tags: ["crunchy", "herbal", "buttery", "firm", "grassy"],
    note: "Baguette, olive oil, rosemary, 400°F until golden. Ten minutes.",
    loves: ["ricotta", "nduja", "burrata", "tapenade", "chevre"],
    perGuest: { amount: 4, unit: "slices" },
    cuts: [
      {
        name: "Overlapped Coins",
        how: "Slice the baguette on a steep bias for long ovals, then shingle them along an edge.",
        motif: "round",
        effort: 2,
      },
    ],
  },
  {
    id: "baguette",
    name: "Baguette rounds",
    cat: "cracker",
    palette: ["#eccf96", "#d4a866", "#f7ecd2"],
    motif: "round",
    tags: ["crunchy", "mild", "buttery", "flaky", "light"],
    note: "Cut within the hour. Nothing goes stale faster or more visibly.",
    loves: ["brie", "epoisses", "pate", "rillettes", "burrata"],
    perGuest: { amount: 4, unit: "slices" },
    cuts: [
      {
        name: "Bias Coins",
        how: "Cut at 45° so each slice is an oval with maximum crust edge.",
        motif: "round",
        effort: 1,
      },
      {
        name: "Torn Hunks",
        how: "Tear the loaf apart by hand into rough hunks and pile them in a linen-lined basket beside the board.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "sourdough",
    name: "Grilled sourdough",
    cat: "cracker",
    palette: ["#e0bc82", "#c49a5e", "#f4ead0"],
    motif: "crumble",
    tags: ["crunchy", "acidic", "chewy", "smoky", "bold"],
    note: "Thick-cut, grilled hard, rubbed with a raw garlic clove while hot.",
    loves: ["burrata", "nduja", "olive-oil", "taleggio", "ricotta"],
    perGuest: { amount: 2, unit: "thick slices" },
    cuts: [
      {
        name: "Charred & Torn",
        how: "Grill thick slices, rub with garlic, then tear into irregular pieces rather than cutting.",
        motif: "crumble",
        flair: "Tear while warm. The ragged edges are where the oil collects.",
        effort: 2,
      },
    ],
  },
  {
    id: "grissini",
    name: "Grissini",
    cat: "cracker",
    palette: ["#e2c28e", "#cba86e", "#f0e2c0"],
    motif: "batons",
    tags: ["crunchy", "mild", "snappy", "light", "buttery"],
    note: "Long, thin, snappable. The vertical element your board is missing.",
    loves: ["prosciutto", "mortadella", "coppa", "boursin"],
    perGuest: { amount: 3, unit: "sticks" },
    cuts: [
      {
        name: "Standing Bundle",
        how: "Stand them upright in a short glass or jar at one end of the board. Instant height.",
        motif: "batons",
        flair: "Height, again. Boards are almost always too flat.",
        effort: 1,
      },
      {
        name: "Laid Diagonal",
        how: "Lay a loose bundle diagonally across a corner, some snapped in half for variation.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "lavash",
    name: "Lavash shards",
    cat: "cracker",
    palette: ["#eee0be", "#dccca4", "#f8f0dc"],
    motif: "crumble",
    tags: ["crunchy", "flaky", "mild", "light", "firm"],
    note: "Bake a sheet until blistered, then shatter it. Very architectural.",
    loves: ["hummus", "feta", "tapenade", "chevre"],
    perGuest: { amount: 3, unit: "shards" },
    cuts: [
      {
        name: "Shattered Planes",
        how: "Break into large irregular shards and stand a few upright against a bowl.",
        motif: "crumble",
        effort: 2,
      },
    ],
  },
  {
    id: "fig-olive-crisp",
    name: "Fig & olive crisps",
    cat: "cracker",
    palette: ["#d4b489", "#bb9a6c", "#6e4a5c"],
    motif: "shingle",
    tags: ["sweet", "briny", "crunchy", "fruity", "bold"],
    note: "The fancy cracker with fruit baked in. Does half the pairing for you.",
    loves: ["chevre", "brie", "roquefort", "manchego"],
    cuts: [
      {
        name: "Fanned Run",
        how: "Overlap in a long run so the fig and olive flecks read as a pattern.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "oat-cake",
    name: "Oat cakes",
    cat: "cracker",
    palette: ["#dfcda2", "#c9b485", "#f0e6ca"],
    motif: "round",
    tags: ["earthy", "crunchy", "nutty", "firm", "mild"],
    note: "Scottish, rough, faintly sweet. The correct vehicle for a blue.",
    loves: ["stilton", "roquefort", "cheddar", "onion-jam"],
    perGuest: { amount: 3, unit: "cakes" },
    cuts: [
      {
        name: "Leaning Stack",
        how: "Stack four or five and lean the stack against a cheese so it doesn't sit flat.",
        motif: "stack",
        effort: 1,
      },
    ],
  },
  {
    id: "pita-chip",
    name: "Pita chips",
    cat: "cracker",
    palette: ["#ead6a8", "#d6bc86", "#f7eed6"],
    motif: "fan",
    tags: ["crunchy", "salty", "firm", "mild", "light"],
    note: "Sturdy enough for hummus, which is the entire job description.",
    loves: ["hummus", "feta", "tapenade"],
    perGuest: { amount: 8, unit: "chips" },
    cuts: [
      {
        name: "Speared Ring",
        how: "Stand them upright in a ring around the rim of the hummus bowl, pointing out.",
        motif: "fan",
        effort: 2,
      },
    ],
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    cat: "spread",
    palette: ["#f0b43c", "#dc9a22", "#fbd980"],
    motif: "bowl",
    tags: ["sweet", "honeyed", "floral", "chewy", "rich"],
    note: "A raw chunk of comb, wax and all. The most photographed thing you can put on a board.",
    loves: ["roquefort", "stilton", "gorgonzola-dolce", "pecorino", "brie", "chevre", "walnut", "fig"],
    cuts: [
      {
        name: "Raw Chunk",
        how: "One square of comb, set directly on the wood, with a knife. It will slowly leak honey into everything nearby, which is the intention.",
        motif: "cube",
        flair: "Put it on a slight rise so the honey runs downhill toward the cheese.",
        effort: 1,
      },
      {
        name: "Drizzle Pool",
        how: "Pour liquid honey into a shallow well and let it spread on its own.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "hot-honey",
    name: "Hot honey",
    cat: "spread",
    palette: ["#efa62c", "#d98a18", "#c74a2c"],
    motif: "bowl",
    tags: ["sweet", "spicy", "honeyed", "bold", "silky"],
    note: "Honey infused with chilli. Turns any mild cheese into an event.",
    loves: ["brie", "feta", "nduja", "pecorino", "peach"],
    cuts: [
      {
        name: "Poured Over",
        how: "Don't bowl it — pour it directly over a warm cheese at the table so it runs down the sides.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "fig-jam",
    name: "Fig jam",
    cat: "spread",
    palette: ["#7a3a52", "#5e2b3f", "#a8607a"],
    motif: "bowl",
    tags: ["sweet", "fruity", "earthy", "spreadable", "rich"],
    note: "The default board jam, and deservedly so. Deep purple-brown.",
    loves: ["brie", "manchego", "prosciutto", "walnut", "chevre"],
    cuts: [
      {
        name: "Swirled Bowl",
        how: "Spoon into a small bowl and swirl the top with the back of a spoon so it catches light.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "apricot-preserve",
    name: "Apricot preserve",
    cat: "spread",
    palette: ["#efa23c", "#d98826", "#f7c882"],
    motif: "bowl",
    tags: ["sweet", "acidic", "fruity", "spreadable", "floral"],
    note: "Brighter and more acidic than fig jam. Good against salty cheese.",
    loves: ["brie", "manchego", "chevre", "aged-gouda"],
    cuts: [
      {
        name: "Small Bowl",
        how: "Serve in the smallest bowl you own — jam is an accent, not a course.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "mustard",
    name: "Whole-grain mustard",
    cat: "spread",
    palette: ["#d9b04c", "#c0963a", "#6e5a2c"],
    motif: "bowl",
    tags: ["acidic", "spicy", "briny", "spreadable", "bold"],
    note: "The seeds give texture as well as heat. Non-negotiable next to pâté.",
    loves: ["pate", "rillettes", "cheddar", "cornichon", "apple"],
    cuts: [
      {
        name: "Bowl & Spoon",
        how: "Small bowl, small spoon, positioned right next to the meat it belongs to.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "onion-jam",
    name: "Caramelised onion jam",
    cat: "spread",
    palette: ["#8a5a3c", "#6e442c", "#b08260"],
    motif: "bowl",
    tags: ["sweet", "umami", "earthy", "spreadable", "rich"],
    note: "Savoury-sweet and deeply brown. The jam for people who don't like jam.",
    loves: ["cheddar", "clothbound-cheddar", "camembert", "pate", "oat-cake"],
    cuts: [
      {
        name: "Rustic Mound",
        how: "Spoon in a rough mound rather than smoothing it flat — you want to see the onion strands.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "hummus",
    name: "Hummus",
    cat: "spread",
    palette: ["#eadfba", "#d8c99c", "#8fa04c"],
    motif: "bowl",
    tags: ["creamy", "earthy", "garlicky", "spreadable", "mild"],
    note: "Make the swoosh. The swoosh is not optional.",
    loves: ["pita-chip", "lavash", "feta", "olive-oil", "castelvetrano"],
    cuts: [
      {
        name: "The Swoosh",
        how: "Spread in a wide shallow bowl and drag the back of a spoon in a spiral to make a channel. Flood it with olive oil, paprika, parsley and whole chickpeas.",
        motif: "bowl",
        flair: "The channel holds the oil. Without it, the oil just runs off the edge.",
        effort: 2,
      },
    ],
  },
  {
    id: "olive-oil",
    name: "Good olive oil",
    cat: "spread",
    palette: ["#c9b44c", "#b09a34", "#8fa04c"],
    motif: "bowl",
    tags: ["grassy", "peppery", "silky", "bitter", "rich"],
    note: "The peppery back-of-the-throat kind. Pour it the day you open it.",
    loves: ["burrata", "sourdough", "mozzarella", "bresaola", "hummus"],
    cuts: [
      {
        name: "Shallow Pool",
        how: "A wide shallow dish, poured deep enough to dunk. Flaky salt and cracked pepper on top.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "tapenade",
    name: "Olive tapenade",
    cat: "spread",
    palette: ["#4a4230", "#372f22", "#6e6444"],
    motif: "bowl",
    tags: ["briny", "salty", "umami", "spreadable", "bold"],
    note: "Dark, salty, intense. A little goes a long way and that's fine.",
    loves: ["crostini", "lavash", "chevre", "olive-oil"],
    cuts: [
      {
        name: "Dark Bowl",
        how: "Its colour is nearly black — put it in a pale bowl or it disappears into the board.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "pepper-jelly",
    name: "Pepper jelly",
    cat: "spread",
    palette: ["#c73a4c", "#a82838", "#e8707c"],
    motif: "bowl",
    tags: ["sweet", "spicy", "acidic", "spreadable", "bold"],
    note: "Sweet heat, translucent red. Spoon it straight over cream cheese.",
    loves: ["soppressata", "water-cracker", "chevre"],
    cuts: [
      {
        name: "Poured Over Cheese",
        how: "Pour over a block of soft cheese so it pools around the base. Serve with a spreader.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "membrillo",
    name: "Membrillo",
    cat: "spread",
    palette: ["#c2503c", "#a53c2c", "#e0806a"],
    motif: "cube",
    tags: ["sweet", "floral", "firm", "fruity", "chewy"],
    note: "Quince paste — sliceable, translucent, ruby-dark. Manchego's soulmate.",
    loves: ["manchego", "jamon-iberico", "marcona-almond", "chorizo"],
    cuts: [
      {
        name: "Matched Triangles",
        how: "Cut into triangles the same size as your Manchego wedges and alternate them in a row.",
        motif: "shingle",
        flair: "Matching the shapes exactly is the kind of detail people notice without noticing.",
        effort: 2,
      },
    ],
  },
  {
    id: "castelvetrano",
    name: "Castelvetrano olives",
    cat: "briny",
    palette: ["#a8bf52", "#8fa63c", "#d0dc90"],
    motif: "cluster",
    tags: ["briny", "buttery", "salty", "mild", "grassy"],
    note: "Bright green, buttery, barely olive-y. The olive for olive sceptics.",
    loves: ["manchego", "chorizo", "feta", "hummus", "finocchiona"],
    cuts: [
      {
        name: "Bowl, Pits In",
        how: "Leave the pits — they taste better. Put out a second small empty bowl for the pits.",
        motif: "bowl",
        flair: "Forgetting the pit bowl is the single most common board mistake.",
        effort: 1,
      },
    ],
  },
  {
    id: "kalamata",
    name: "Kalamata olives",
    cat: "briny",
    palette: ["#5e2f3c", "#46222c", "#8a5060"],
    motif: "cluster",
    tags: ["briny", "salty", "winey", "bold", "umami"],
    note: "Deep purple-black and properly assertive.",
    loves: ["feta", "lavash", "hummus", "tapenade"],
    cuts: [
      {
        name: "Marinated Bowl",
        how: "Warm briefly in olive oil with lemon peel, oregano and a smashed garlic clove.",
        motif: "bowl",
        effort: 2,
      },
    ],
  },
  {
    id: "cornichon",
    name: "Cornichons",
    cat: "briny",
    palette: ["#7d9a3c", "#63802c", "#b4c46e"],
    motif: "cluster",
    tags: ["acidic", "briny", "snappy", "crunchy", "light"],
    note: "Tiny, sour, crunchy. The reset button between rich bites.",
    loves: ["pate", "rillettes", "gruyere", "mustard", "comte"],
    cuts: [
      {
        name: "Fanned Whole",
        how: "Slice each one lengthways three times from the tip, stopping short of the stem, and press to fan.",
        motif: "fan",
        flair: "Thirty seconds of work that makes a jar of pickles look intentional.",
        effort: 2,
      },
      {
        name: "Loose Pile",
        how: "Straight from the jar into a heap, stems all pointing the same way.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "pickled-onion",
    name: "Pickled red onion",
    cat: "briny",
    palette: ["#c25a7c", "#a34462", "#e090a8"],
    motif: "cluster",
    tags: ["acidic", "briny", "snappy", "spicy", "light"],
    note: "Fifteen minutes in vinegar turns them shocking pink.",
    loves: ["pate", "cheddar", "hummus", "chevre"],
    cuts: [
      {
        name: "Tangled Nest",
        how: "Lift them out in a tangle with tongs so the rings stay interlocked and stand up.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "artichoke",
    name: "Marinated artichokes",
    cat: "briny",
    palette: ["#a8b070", "#8e9656", "#d4d8a0"],
    motif: "cluster",
    tags: ["briny", "acidic", "earthy", "silky", "herbal"],
    note: "Grilled quarters in oil. Meaty enough to matter on a vegetarian board.",
    loves: ["olive-oil", "parmigiano", "crostini", "mozzarella"],
    cuts: [
      {
        name: "Quartered, Leaves Out",
        how: "Arrange cut-side up so the layered leaves show. That structure is the appeal.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "peperoncini",
    name: "Peperoncini",
    cat: "briny",
    palette: ["#b4c44c", "#9aaa36", "#d8e084"],
    motif: "cluster",
    tags: ["acidic", "spicy", "briny", "snappy", "light"],
    note: "Barely hot, mostly tangy. Their curl adds movement to a flat area.",
    loves: ["genoa", "giardiniera", "olive-oil"],
    cuts: [
      {
        name: "Whole, Stems On",
        how: "Whole with stems, arranged so the curves all sweep the same direction.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "giardiniera",
    name: "Giardiniera",
    cat: "briny",
    palette: ["#dcae3c", "#c4962c", "#8fa04c"],
    motif: "scatter",
    tags: ["acidic", "spicy", "crunchy", "briny", "bold"],
    note: "Pickled vegetable confetti. Brings four colours in one jar.",
    loves: ["soppressata", "genoa", "olive-oil"],
    cuts: [
      {
        name: "Drained Heap",
        how: "Drain well — a wet pile bleeds brine across the board and softens the crackers.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "caper-berry",
    name: "Caper berries",
    cat: "briny",
    palette: ["#6e7d3c", "#56642c", "#9aa86e"],
    motif: "cluster",
    tags: ["briny", "salty", "acidic", "bitter", "firm"],
    note: "Capers grown up, with a stem. Look like tiny olives, taste sharper.",
    loves: ["bresaola", "olive-oil", "parmigiano", "tapenade"],
    cuts: [
      {
        name: "Stems Radiating",
        how: "Lay them with the stems fanning outward from a centre point like a starburst.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },

  // ─── Added in the expansion ────────────────────────────────────────────────
  {
    id: "rye-crisp",
    name: "Rye crispbread",
    cat: "cracker",
    palette: ["#c9a878", "#b08e5e", "#6e5438"],
    motif: "crumble",
    tags: ["earthy", "crunchy", "bitter", "firm", "nutty"],
    perGuest: { amount: 3, unit: "crispbreads" },
    note: "Dark, dense, faintly sour. Built for smoked fish and strong cheese.",
    loves: ["smoked-salmon", "roquefort", "cream-cheese", "pickled-onion"],
    cuts: [
      {
        name: "Snapped in Halves",
        how: "Snap each sheet roughly in two — the jagged break looks better than the scored line.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "parmesan-crisp",
    name: "Parmesan crisps",
    cat: "cracker",
    palette: ["#e8c882", "#d4b062", "#f2e2b8"],
    motif: "crumble",
    tags: ["salty", "umami", "crunchy", "nutty", "flaky"],
    perGuest: { amount: 3, unit: "crisps" },
    note: "Just baked cheese. Gluten-free by accident and gone in minutes.",
    loves: ["prosciutto", "olive-oil", "grape-red", "bresaola"],
    cuts: [
      {
        name: "Lacy Discs",
        how: "Bake tablespoons of grated Parmesan at 400°F for six minutes until lacy, then cool on the pan.",
        motif: "round",
        flair: "Drape them over a rolling pin while warm and they set into tuiles.",
        effort: 2,
      },
    ],
  },
  {
    id: "everything-cracker",
    name: "Everything crackers",
    cat: "cracker",
    palette: ["#e2c896", "#cbae76", "#3c342c"],
    motif: "fan",
    tags: ["salty", "garlicky", "crunchy", "nutty", "bold"],
    note: "Sesame, poppy, garlic, onion. Does a lot of the seasoning for you.",
    loves: ["cream-cheese", "smoked-salmon", "labneh", "chevre"],
    cuts: [
      {
        name: "Toppled Run",
        how: "Cascade them along an edge, seeded face up so the speckle shows.",
        motif: "fan",
        effort: 1,
      },
    ],
  },
  {
    id: "charcoal-cracker",
    name: "Charcoal crackers",
    cat: "cracker",
    palette: ["#3c3a3c", "#2a282a", "#6e6a6e"],
    motif: "fan",
    tags: ["earthy", "crunchy", "mild", "firm", "bold"],
    note: "Jet black. Nothing makes a pale cheese pop harder.",
    loves: ["chevre", "brie", "triple-creme", "burrata"],
    cuts: [
      {
        name: "Fanned Against Pale Cheese",
        how: "Always place these touching something white. The contrast is the entire reason to buy them.",
        motif: "fan",
        effort: 1,
      },
    ],
  },
  {
    id: "brioche-toast",
    name: "Brioche toasts",
    cat: "cracker",
    palette: ["#f2d9a2", "#dcbe7e", "#f7ecd4"],
    motif: "round",
    perGuest: { amount: 3, unit: "toasts" },
    tags: ["buttery", "sweet", "crunchy", "rich", "flaky"],
    note: "Sweet, eggy, golden. The correct vehicle for anything expensive.",
    loves: ["foie-gras", "fig-jam", "triple-creme", "mascarpone"],
    cuts: [
      {
        name: "Toasted to Order",
        how: "Cut fingers, toast until the edges catch, and bring them out warm.",
        motif: "batons",
        effort: 2,
      },
    ],
  },
  {
    id: "focaccia",
    name: "Focaccia",
    cat: "cracker",
    palette: ["#eeca8a", "#d9ae66", "#8fa04c"],
    perGuest: { amount: 2, unit: "squares" },
    motif: "cube",
    tags: ["buttery", "herbal", "chewy", "salty", "rich"],
    note: "Dimpled, oily, rosemary-strewn. Tear it, never slice it.",
    loves: ["mortadella", "olive-oil", "sun-dried-tomato", "burrata"],
    cuts: [
      {
        name: "Torn Squares",
        how: "Cut into squares, then tear each one roughly in half so the crumb shows.",
        motif: "cube",
        effort: 1,
      },
    ],
  },
  {
    id: "pretzel-crisp",
    name: "Pretzel crisps",
    cat: "cracker",
    palette: ["#c9945e", "#b07a44", "#f2e8d4"],
    motif: "fan",
    tags: ["salty", "crunchy", "snappy", "mild", "firm"],
    note: "Flat, salty, sturdy. The one everyone reaches for without thinking.",
    loves: ["cheddar", "mustard", "onion-jam", "smoked-gouda"],
    cuts: [
      {
        name: "Standing Fan",
        how: "Wedge them upright against a cheese so they stand in a row.",
        motif: "fan",
        effort: 1,
      },
    ],
  },
  {
    id: "melba-toast",
    name: "Melba toast",
    cat: "cracker",
    palette: ["#e8d0a0", "#d4b880", "#f4e8cc"],
    motif: "crumble",
    tags: ["crunchy", "mild", "flaky", "light", "firm"],
    note: "Thin, curled, faintly retro. Fragile in the best way.",
    loves: ["pate", "rillettes", "foie-gras", "mustard"],
    cuts: [
      {
        name: "Piled Loose",
        how: "Heap them loosely — stacking snaps them.",
        motif: "crumble",
        effort: 1,
      },
    ],
  },
  {
    id: "apple-butter",
    name: "Apple butter",
    cat: "spread",
    palette: ["#8a5230", "#6e3e22", "#b07a50"],
    motif: "bowl",
    tags: ["sweet", "earthy", "spreadable", "fruity", "rich"],
    note: "Apples cooked down for hours until dark and spiced. Autumn in a jar.",
    loves: ["clothbound-cheddar", "cheddar", "oat-cake", "smoked-gouda"],
    cuts: [
      {
        name: "Small Dark Bowl",
        how: "It's nearly black — put it in a pale bowl and swirl the top.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "truffle-honey",
    name: "Truffle honey",
    cat: "spread",
    palette: ["#e8a82c", "#cf8c18", "#6e5438"],
    motif: "bowl",
    tags: ["sweet", "earthy", "honeyed", "umami", "bold"],
    note: "Honey infused with black truffle. Extravagant on a hard sheep's cheese.",
    loves: ["pecorino", "manchego", "parmigiano", "truffle-salami"],
    cuts: [
      {
        name: "Drizzled at the Table",
        how: "Pour it over the cheese in front of people rather than bowling it up separately.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "balsamic-glaze",
    name: "Balsamic glaze",
    cat: "spread",
    palette: ["#3c2028", "#2a1418", "#6e4450"],
    motif: "bowl",
    tags: ["acidic", "sweet", "silky", "winey", "bold"],
    note: "Reduced until syrupy. Draws a dark line across anything pale.",
    loves: ["burrata", "mozzarella", "parmigiano", "strawberry", "cherry-tomato"],
    cuts: [
      {
        name: "Zig-Zag Drizzle",
        how: "Drizzle in a fast zig-zag straight across the board rather than pooling it in a dish.",
        motif: "bowl",
        flair: "A dark line across pale cheese is the cheapest styling trick there is.",
        effort: 1,
      },
    ],
  },
  {
    id: "whipped-feta",
    name: "Whipped feta",
    cat: "spread",
    palette: ["#fbf8ee", "#eae4d2", "#c73a34"],
    motif: "bowl",
    tags: ["salty", "creamy", "acidic", "spreadable", "bold"],
    note: "Feta blitzed with yoghurt and lemon until it's a cloud. Deeply moreish.",
    loves: ["pita-chip", "olive-oil", "pomegranate", "cucumber", "hot-honey"],
    cuts: [
      {
        name: "Swooshed with Chilli Oil",
        how: "Spread wide, drag a channel through it, and flood with chilli oil and oregano.",
        motif: "bowl",
        effort: 2,
      },
    ],
  },
  {
    id: "romesco",
    name: "Romesco",
    cat: "spread",
    palette: ["#c24a2c", "#a5361c", "#e0805e"],
    motif: "bowl",
    tags: ["smoky", "nutty", "spicy", "spreadable", "bold"],
    note: "Roasted pepper and almond, thickened with bread. Catalan and glorious.",
    loves: ["bell-pepper", "carrot", "manchego", "grissini", "chorizo"],
    cuts: [
      {
        name: "Rustic Bowl",
        how: "Leave it coarse — you want to see the almond. Pool oil on top.",
        motif: "bowl",
        effort: 2,
      },
    ],
  },
  {
    id: "muhammara",
    name: "Muhammara",
    cat: "spread",
    palette: ["#a8402c", "#8a2e1c", "#cf6a4a"],
    motif: "bowl",
    tags: ["smoky", "nutty", "spicy", "acidic", "spreadable"],
    note: "Red pepper and walnut with pomegranate molasses. Sweet-hot and tangy.",
    loves: ["lavash", "labneh", "cucumber", "feta", "walnut"],
    cuts: [
      {
        name: "Walnut-Topped",
        how: "Spoon into a bowl and crown with walnut halves and a slick of oil.",
        motif: "bowl",
        effort: 2,
      },
    ],
  },
  {
    id: "mango-chutney",
    name: "Mango chutney",
    cat: "spread",
    palette: ["#dc9a2c", "#c48018", "#8a5230"],
    motif: "bowl",
    tags: ["sweet", "spicy", "acidic", "tropical", "bold"],
    note: "Sweet, sour and warm with spice. Brilliant against a sharp cheddar.",
    loves: ["cheddar", "clothbound-cheddar", "oat-cake", "biltong"],
    cuts: [
      {
        name: "Chunky Spoonful",
        how: "Pick a chunky one and don't smooth it out — the fruit pieces are the appeal.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "cranberry-sauce",
    name: "Cranberry sauce",
    cat: "spread",
    palette: ["#b02638", "#921c2c", "#d95a68"],
    motif: "bowl",
    tags: ["acidic", "sweet", "fruity", "berry", "spreadable"],
    note: "Whole-berry, not jellied. The December board's non-negotiable.",
    loves: ["stilton", "wensleydale-cranberry", "brie", "oat-cake", "chestnut"],
    cuts: [
      {
        name: "Loose in a Bowl",
        how: "Whole-berry sauce, spooned rough so the burst berries show.",
        motif: "bowl",
        effort: 1,
      },
    ],
  },
  {
    id: "sun-dried-tomato",
    name: "Sun-dried tomatoes",
    cat: "briny",
    palette: ["#a8302c", "#8a201e", "#cf5a4a"],
    motif: "cluster",
    tags: ["umami", "acidic", "chewy", "salty", "bold"],
    note: "In oil, not the leathery dry ones. Concentrated and jammy.",
    loves: ["mozzarella", "olive-oil", "finocchiona", "basil", "provolone"],
    cuts: [
      {
        name: "Oil-Slicked Pile",
        how: "Lift them out with some of their oil and pile them so they glisten.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "roasted-pepper",
    name: "Roasted red peppers",
    cat: "briny",
    palette: ["#c73a2c", "#a8281c", "#e0704a"],
    motif: "drape",
    tags: ["sweet", "smoky", "silky", "acidic", "juicy"],
    note: "Blistered, peeled, in oil. Silky and sweet, and a big hit of red.",
    loves: ["manchego", "romesco", "olive-oil", "mozzarella", "chorizo"],
    cuts: [
      {
        name: "Torn Ribbons",
        how: "Tear into wide ribbons and lay them in loose folds so they catch the light.",
        motif: "drape",
        effort: 1,
      },
    ],
  },
  {
    id: "pickled-mushroom",
    name: "Pickled mushrooms",
    cat: "briny",
    palette: ["#8a7452", "#6e5a3c", "#c4b088"],
    motif: "cluster",
    tags: ["earthy", "acidic", "briny", "umami", "chewy"],
    note: "Tiny whole buttons in vinegar and herbs. Savoury and underused.",
    loves: ["taleggio", "comte", "pate", "rye-crisp"],
    cuts: [
      {
        name: "Whole, Stems On",
        how: "Keep them whole with the stems attached and drain them well.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
];
