import type { Item } from "../types";

/** Fresh and dried fruit. Palettes are [base, mid, accent] and feed the motif
 *  generators; `cuts` is the how-to-make-it-look-good payload. */
export const PRODUCE: Item[] = [
  {
    id: "peach",
    name: "Peach",
    cat: "fruit",
    palette: ["#f6a95f", "#e88b46", "#d1452f"],
    motif: "fan",
    tags: ["sweet", "juicy", "stone-fruit", "floral", "fruity"],
    season: [6, 7, 8, 9],
    note: "At peak, a ripe peach outclasses anything else you could buy.",
    loves: ["burrata", "prosciutto", "chevre", "gorgonzola-dolce", "basil", "honeycomb", "ricotta"],
    cuts: [
      {
        name: "Fruit Flower",
        how: "Slice as thin as you can hold, then stand the slices on edge in a ring, each overlapping the last by half. Curl the final few tightly and set them in the middle as the bud.",
        motif: "flower",
        flair: "Works on anything that slices into a crescent — the thinner the slice, the more it looks like a bloom.",
        effort: 3,
      },
      {
        name: "Fanned Half-Moons",
        how: "Halve, stone, then slice each half into thin crescents. Keep the slices together and press gently sideways so they fan out like a deck.",
        motif: "fan",
        flair: "Leave the skin on — that red blush is the best colour on the board.",
        effort: 2,
      },
      {
        name: "Grilled Cheeks",
        how: "Cut the cheeks off, grill cut-side down for two minutes until caramelised, and serve warm next to something creamy.",
        motif: "halved",
        effort: 3,
      },
      {
        name: "Torn Wedges",
        how: "If it's a proper freestone, tear it apart with your hands. The ragged surface holds honey.",
        motif: "halved",
        effort: 1,
      },
    ],
  },
  {
    id: "nectarine",
    name: "Nectarine",
    cat: "fruit",
    palette: ["#ef8f52", "#dc7038", "#b52f2c"],
    motif: "fan",
    tags: ["sweet", "juicy", "stone-fruit", "acidic", "fruity"],
    season: [6, 7, 8, 9],
    note: "A peach without the fuzz, usually a touch sharper.",
    loves: ["burrata", "prosciutto", "chevre", "basil"],
    cuts: [
      {
        name: "Thin Fan",
        how: "Slice into thin wedges skin-on and fan them in a quarter circle.",
        motif: "fan",
        effort: 1,
      },
    ],
  },
  {
    id: "fig",
    name: "Fresh fig",
    cat: "fruit",
    palette: ["#7a4a72", "#5f3559", "#c85a6a"],
    motif: "halved",
    tags: ["sweet", "honeyed", "floral", "juicy", "fruity"],
    season: [7, 8, 9],
    note: "Split one open and the interior does all the work for you.",
    loves: ["prosciutto", "gorgonzola-dolce", "honeycomb", "chevre", "walnut", "burrata"],
    cuts: [
      {
        name: "Fruit Flower",
        how: "Slice as thin as you can hold, then stand the slices on edge in a ring, each overlapping the last by half. Curl the final few tightly and set them in the middle as the bud.",
        motif: "flower",
        flair: "Works on anything that slices into a crescent — the thinner the slice, the more it looks like a bloom.",
        effort: 3,
      },
      {
        name: "Quartered Blossom",
        how: "Stand the fig up and cut down twice, not quite through the base, then press the quarters open like petals.",
        motif: "halved",
        flair: "The pink interior against a dark board is the whole reason to buy figs.",
        effort: 2,
      },
      {
        name: "Simple Halves",
        how: "Halve lengthways, cut face up, scattered in threes.",
        motif: "halved",
        effort: 1,
      },
    ],
  },
  {
    id: "grape-red",
    name: "Red grapes",
    cat: "fruit",
    palette: ["#7e3f6d", "#63305a", "#a76490"],
    motif: "cluster",
    tags: ["sweet", "juicy", "winey", "snappy", "fruity"],
    season: [8, 9, 10],
    note: "The default gap-filler, and genuinely good at it.",
    loves: ["brie", "cheddar", "havarti", "walnut"],
    cuts: [
      {
        name: "Small Clusters, Stems On",
        how: "Snip into little clusters of five or six with scissors. Loose single grapes roll around and look like spare parts.",
        motif: "cluster",
        flair: "Stems on. Always stems on.",
        effort: 1,
      },
      {
        name: "Roasted on the Vine",
        how: "Roast whole clusters at 400°F for 15 minutes until they blister and slump. Serve warm.",
        motif: "cluster",
        effort: 3,
      },
    ],
  },
  {
    id: "grape-green",
    name: "Green grapes",
    cat: "fruit",
    palette: ["#b9c95e", "#a3b44b", "#d8e08a"],
    motif: "cluster",
    tags: ["sweet", "acidic", "snappy", "juicy", "light"],
    season: [8, 9, 10],
    note: "Sharper than red, and a much-needed pale green on a warm board.",
    loves: ["brie", "gruyere", "havarti"],
    cuts: [
      {
        name: "Small Clusters, Stems On",
        how: "Scissors, not fingers. Cut clusters that sit up rather than sprawl.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "champagne-grape",
    name: "Champagne grapes",
    cat: "fruit",
    palette: ["#8a4a6e", "#6e3a58", "#b47a9a"],
    motif: "cluster",
    tags: ["sweet", "juicy", "winey", "light", "fruity"],
    season: [7, 8, 9],
    note: "Tiny, seedless, dramatic. Sold as fussy little bunches.",
    loves: ["triple-creme", "brie", "chevre"],
    cuts: [
      {
        name: "Draped Bunch",
        how: "Drape a whole bunch over the edge of the board so it spills off. Instant abundance.",
        motif: "cluster",
        flair: "Anything hanging off the edge makes a board look twice as full.",
        effort: 1,
      },
    ],
  },
  {
    id: "strawberry",
    name: "Strawberry",
    cat: "fruit",
    palette: ["#dd3b3f", "#bf2a30", "#6ea24a"],
    motif: "halved",
    tags: ["sweet", "acidic", "juicy", "berry", "fruity"],
    season: [4, 5, 6, 7],
    note: "Buy them with the leaves on and keep the leaves on.",
    loves: ["brie", "chevre", "dark-chocolate", "basil", "honeycomb"],
    cuts: [
      {
        name: "Fruit Flower",
        how: "Slice as thin as you can hold, then stand the slices on edge in a ring, each overlapping the last by half. Curl the final few tightly and set them in the middle as the bud.",
        motif: "flower",
        flair: "Works on anything that slices into a crescent — the thinner the slice, the more it looks like a bloom.",
        effort: 3,
      },
      {
        name: "Halved, Leaves On",
        how: "Halve lengthways straight through the green top. The leaf half-moon is free decoration.",
        motif: "halved",
        effort: 1,
      },
      {
        name: "Fanned Whole",
        how: "Slice from tip almost to the hull four or five times, then press to fan while the berry stays in one piece.",
        motif: "fan",
        effort: 2,
      },
    ],
  },
  {
    id: "blackberry",
    name: "Blackberry",
    cat: "fruit",
    palette: ["#4a2b4e", "#38203c", "#7b5280"],
    motif: "cluster",
    tags: ["sweet", "acidic", "berry", "juicy", "earthy"],
    season: [7, 8, 9],
    note: "The deepest colour available to you. Use it against pale cheese.",
    loves: ["chevre", "brie", "honeycomb", "thyme"],
    cuts: [
      {
        name: "Scattered Threes",
        how: "Tuck in odd-numbered clusters, never in a line. They should look dropped, not placed.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "raspberry",
    name: "Raspberry",
    cat: "fruit",
    palette: ["#d9425c", "#bd3049", "#eb7f92"],
    motif: "cluster",
    tags: ["acidic", "sweet", "berry", "floral", "juicy"],
    season: [6, 7, 8, 9],
    note: "Fragile, tart, and the exact pink nothing else on the board is.",
    loves: ["triple-creme", "chevre", "dark-chocolate"],
    cuts: [
      {
        name: "Balanced Upright",
        how: "Stand them hollow-side down in small groups so they don't collapse.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "blueberry",
    name: "Blueberry",
    cat: "fruit",
    palette: ["#4b5c92", "#3a4874", "#8b9ac4"],
    motif: "scatter",
    tags: ["sweet", "berry", "juicy", "mild", "light"],
    season: [6, 7, 8],
    note: "The only true blue on any board. Worth it for that alone.",
    loves: ["chevre", "brie", "honeycomb"],
    cuts: [
      {
        name: "Poured Drift",
        how: "Pour them into a gap and let them find their own edge. They do the gap-filling for you.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "apple",
    name: "Apple",
    cat: "fruit",
    palette: ["#cf3f3f", "#b02f30", "#f4e8c8"],
    motif: "fan",
    tags: ["sweet", "acidic", "crunchy", "snappy", "fruity"],
    season: [9, 10, 11, 12],
    note: "Honeycrisp for snap, Pink Lady for tartness. Never Red Delicious.",
    loves: ["cheddar", "gruyere", "comte", "mustard", "walnut", "smoked-gouda"],
    cuts: [
      {
        name: "Fruit Flower",
        how: "Slice as thin as you can hold, then stand the slices on edge in a ring, each overlapping the last by half. Curl the final few tightly and set them in the middle as the bud.",
        motif: "flower",
        flair: "Works on anything that slices into a crescent — the thinner the slice, the more it looks like a bloom.",
        effort: 3,
      },
      {
        name: "Skin-On Fan",
        how: "Quarter, core, then slice thin with the skin on and fan the slices so the red edges stripe the fan.",
        motif: "fan",
        flair: "Lemon water for 30 seconds stops the browning without tasting of lemon.",
        effort: 1,
      },
      {
        name: "Matchsticks",
        how: "Cut into fine batons and pile them like kindling next to a sharp cheddar.",
        motif: "batons",
        effort: 2,
      },
    ],
  },
  {
    id: "pear",
    name: "Pear",
    cat: "fruit",
    palette: ["#c9cf6a", "#b0b854", "#f0ecc8"],
    motif: "fan",
    tags: ["sweet", "floral", "juicy", "silky", "fruity"],
    season: [8, 9, 10, 11],
    note: "Ripe enough to yield at the neck. Bosc holds its shape best.",
    loves: ["gorgonzola-dolce", "roquefort", "stilton", "taleggio", "walnut", "honeycomb", "comte"],
    cuts: [
      {
        name: "Fruit Flower",
        how: "Slice as thin as you can hold, then stand the slices on edge in a ring, each overlapping the last by half. Curl the final few tightly and set them in the middle as the bud.",
        motif: "flower",
        flair: "Works on anything that slices into a crescent — the thinner the slice, the more it looks like a bloom.",
        effort: 3,
      },
      {
        name: "Long Fan",
        how: "Halve, core with a melon baller for a clean crescent, then slice lengthways and fan into a long teardrop.",
        motif: "fan",
        effort: 2,
      },
    ],
  },
  {
    id: "persimmon",
    name: "Persimmon",
    cat: "fruit",
    palette: ["#e87a2c", "#cd6120", "#f6b768"],
    motif: "shingle",
    tags: ["sweet", "honeyed", "floral", "firm", "fruity"],
    season: [10, 11, 12],
    note: "Fuyu, eaten firm like an apple. Late autumn's best colour.",
    loves: ["chevre", "prosciutto", "walnut", "honeycomb"],
    cuts: [
      {
        name: "Fruit Flower",
        how: "Slice as thin as you can hold, then stand the slices on edge in a ring, each overlapping the last by half. Curl the final few tightly and set them in the middle as the bud.",
        motif: "flower",
        flair: "Works on anything that slices into a crescent — the thinner the slice, the more it looks like a bloom.",
        effort: 3,
      },
      {
        name: "Crosswise Coins",
        how: "Slice across the fruit, not down — you get a faint star pattern in the middle of every coin.",
        motif: "shingle",
        flair: "That hidden star is the best-kept secret in fruit.",
        effort: 1,
      },
    ],
  },
  {
    id: "pomegranate",
    name: "Pomegranate",
    cat: "fruit",
    palette: ["#b32636", "#93192a", "#e05a63"],
    motif: "scatter",
    tags: ["acidic", "sweet", "snappy", "juicy", "fruity"],
    season: [10, 11, 12, 1],
    note: "Jewels. Scatter them over everything and the board looks finished.",
    loves: ["chevre", "feta", "mint", "honeycomb"],
    cuts: [
      {
        name: "Scattered Jewels",
        how: "Halve underwater and knock the seeds free with a spoon — no juice on the ceiling. Scatter over pale cheeses last.",
        motif: "scatter",
        flair: "This is the confetti step. Do it after everything else is placed.",
        effort: 2,
      },
    ],
  },
  {
    id: "cherry",
    name: "Cherries",
    cat: "fruit",
    palette: ["#9e1f34", "#821526", "#c74a58"],
    motif: "cluster",
    tags: ["sweet", "acidic", "juicy", "winey", "fruity"],
    season: [5, 6, 7],
    note: "Leave the stems on and put out a small bowl for the pits.",
    loves: ["dark-chocolate", "brie", "chevre", "marcona-almond"],
    cuts: [
      {
        name: "Stems Up",
        how: "Pile them with the stems pointing up and out. They tangle and hold a mound shape.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "melon",
    name: "Cantaloupe",
    cat: "fruit",
    palette: ["#f0a35c", "#dc8843", "#c9e0a0"],
    motif: "fan",
    tags: ["sweet", "juicy", "floral", "light", "fruity"],
    season: [6, 7, 8, 9],
    note: "The other half of the oldest pairing in this whole tradition.",
    loves: ["prosciutto", "mint", "feta", "jamon-iberico"],
    cuts: [
      {
        name: "Prosciutto Saddles",
        how: "Cut thin crescents with the rind left on as a handle, then drape prosciutto over each.",
        motif: "fan",
        effort: 2,
      },
      {
        name: "Balled",
        how: "Melon-baller spheres, piled in a bowl with torn mint and a squeeze of lime.",
        motif: "cluster",
        effort: 2,
      },
    ],
  },
  {
    id: "citrus",
    name: "Citrus supremes",
    cat: "fruit",
    palette: ["#f2932f", "#dc7a1c", "#fcd08a"],
    motif: "fan",
    tags: ["acidic", "citrus", "juicy", "light", "floral"],
    season: [12, 1, 2, 3],
    note: "Blood orange, cara cara, ruby grapefruit. Winter's answer to berries.",
    loves: ["chevre", "ricotta", "olive-oil", "pistachio", "mint"],
    cuts: [
      {
        name: "Supremed Segments",
        how: "Cut the peel and pith off in strips, then cut each segment free of its membrane. Fan them overlapping.",
        motif: "fan",
        flair: "Squeeze the spent membranes over the board for a free glaze.",
        effort: 3,
      },
      {
        name: "Thin Wheels",
        how: "Slice straight across into thin wheels, peel and all, and lay them shingled.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "apricot",
    name: "Fresh apricot",
    cat: "fruit",
    palette: ["#f0a94c", "#dc9036", "#f7cf90"],
    motif: "halved",
    tags: ["sweet", "acidic", "stone-fruit", "floral", "fruity"],
    season: [5, 6, 7],
    note: "A short season and an underrated one. Tart, perfumed, small.",
    loves: ["chevre", "brie", "honeycomb", "pistachio"],
    cuts: [
      {
        name: "Split Halves",
        how: "Halve and twist apart, cut side up so the orange interior faces the room.",
        motif: "halved",
        effort: 1,
      },
    ],
  },
  {
    id: "plum",
    name: "Plum",
    cat: "fruit",
    palette: ["#6e3350", "#56253f", "#a8637f"],
    motif: "fan",
    tags: ["sweet", "acidic", "juicy", "winey", "stone-fruit"],
    season: [6, 7, 8, 9],
    note: "Deep purple skin, amber flesh — the best two-tone slice you can cut.",
    loves: ["gorgonzola-dolce", "prosciutto", "chevre", "honeycomb"],
    cuts: [
      {
        name: "Fruit Flower",
        how: "Slice as thin as you can hold, then stand the slices on edge in a ring, each overlapping the last by half. Curl the final few tightly and set them in the middle as the bud.",
        motif: "flower",
        flair: "Works on anything that slices into a crescent — the thinner the slice, the more it looks like a bloom.",
        effort: 3,
      },
      {
        name: "Two-Tone Wedges",
        how: "Cut thin wedges so every one carries a band of dark skin against the pale flesh, then fan.",
        motif: "fan",
        effort: 1,
      },
    ],
  },
  {
    id: "kumquat",
    name: "Kumquat",
    cat: "fruit",
    palette: ["#f0902c", "#d9761a", "#8fa05c"],
    motif: "cluster",
    tags: ["acidic", "citrus", "bitter", "snappy", "floral"],
    season: [12, 1, 2, 3],
    note: "Eat the whole thing — sweet skin, sour inside. Tiny and dramatic.",
    loves: ["chevre", "prosciutto", "honeycomb"],
    cuts: [
      {
        name: "Halved & Whole",
        how: "Halve half of them, leave the rest whole with leaves attached if you can find them on the branch.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-apricot",
    name: "Dried apricot",
    cat: "dried",
    palette: ["#e08a3c", "#c8712c", "#f2b06a"],
    motif: "shingle",
    tags: ["sweet", "chewy", "acidic", "fruity", "honeyed"],
    note: "Get the Turkish ones — plump, dark, unsulphured, actually apricot.",
    loves: ["aged-gouda", "brie", "marcona-almond", "pistachio"],
    cuts: [
      {
        name: "Overlapping Coins",
        how: "Shingle them in a curving line so they read as one ribbon of orange.",
        motif: "shingle",
        effort: 1,
      },
      {
        name: "Stuffed",
        how: "Pipe goat cheese into each one and top with a pistachio.",
        motif: "cluster",
        effort: 2,
      },
    ],
  },
  {
    id: "date",
    name: "Medjool date",
    cat: "dried",
    palette: ["#7a4426", "#5f321b", "#a86a42"],
    motif: "scatter",
    tags: ["sweet", "chewy", "honeyed", "rich", "earthy"],
    note: "Caramel in fruit form. Sticky enough to hold anything you stuff in.",
    loves: ["roquefort", "stilton", "marcona-almond", "chevre", "aged-gouda"],
    cuts: [
      {
        name: "Split & Stuffed",
        how: "Slit lengthways, pit, and press in blue cheese or goat cheese so it bulges out the top. One almond on each.",
        motif: "scatter",
        flair: "Wrap in half a slice of prosciutto and broil for four minutes.",
        effort: 2,
      },
    ],
  },
  {
    id: "dried-fig",
    name: "Dried fig",
    cat: "dried",
    palette: ["#8a6a45", "#6e5233", "#b59468"],
    motif: "halved",
    tags: ["sweet", "chewy", "earthy", "honeyed", "nutty"],
    note: "Mission figs, halved so the seedy interior shows.",
    loves: ["roquefort", "stilton", "walnut", "honeycomb", "manchego"],
    cuts: [
      {
        name: "Halved Face-Up",
        how: "Halve lengthways and lay cut-side up — the seed pattern is the texture you're after.",
        motif: "halved",
        effort: 1,
      },
    ],
  },
  {
    id: "golden-raisin",
    name: "Golden raisins",
    cat: "dried",
    palette: ["#d9ac52", "#c0933c", "#ecc97e"],
    motif: "scatter",
    tags: ["sweet", "chewy", "fruity", "honeyed", "light"],
    note: "Better than they sound. Plump them in warm sherry for ten minutes.",
    loves: ["manchego", "aged-gouda", "pistachio"],
    cuts: [
      {
        name: "Loose Scatter",
        how: "Sprinkle into the seams between larger items — they fill the last gaps nothing else will.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-cherry",
    name: "Dried cherries",
    cat: "dried",
    palette: ["#8a2733", "#6e1c26", "#b04a52"],
    motif: "scatter",
    tags: ["sweet", "acidic", "chewy", "fruity", "bold"],
    note: "Tart Montmorency, not the sugary kind. Deep red punctuation.",
    loves: ["dark-chocolate", "aged-gouda", "pecan", "brie"],
    cuts: [
      {
        name: "Tight Piles",
        how: "Keep them in tight small piles rather than scattered — the colour is strongest concentrated.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "candied-orange",
    name: "Candied orange",
    cat: "dried",
    palette: ["#e8952f", "#d07a1c", "#f7c46a"],
    motif: "batons",
    tags: ["sweet", "citrus", "chewy", "bitter", "floral"],
    note: "Half-dipped in dark chocolate if you're feeling grand.",
    loves: ["dark-chocolate", "marcona-almond", "ricotta"],
    cuts: [
      {
        name: "Crossed Batons",
        how: "Stack the strips in a criss-cross pile so they build height instead of lying flat.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-mango",
    name: "Dried mango",
    cat: "dried",
    palette: ["#f0a52c", "#d98a18", "#f7c76a"],
    tags: ["sweet", "tropical", "chewy", "acidic", "fruity"],
    motif: "shingle",
    note: "Chewy, bright, and a tropical note most boards don't have.",
    loves: ["chevre", "cashew", "hot-honey"],
    cuts: [
      {
        name: "Torn Strips",
        how: "Tear into ragged strips and pile loosely — cut edges look manufactured.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "prune",
    name: "Dried plum",
    cat: "dried",
    palette: ["#4e2f30", "#3a2224", "#7a5250"],
    motif: "scatter",
    tags: ["sweet", "chewy", "earthy", "rich", "winey"],
    note: "Call them dried plums and people will actually eat them.",
    loves: ["stilton", "walnut", "pate"],
    cuts: [
      {
        name: "Armagnac-Soaked",
        how: "Soak in warm Armagnac or tea for an hour until they plump, then serve glossy.",
        motif: "scatter",
        effort: 2,
      },
    ],
  },

  // ─── Added in the expansion ────────────────────────────────────────────────
  {
    id: "watermelon",
    name: "Watermelon",
    cat: "fruit",
    palette: ["#e8455e", "#cf3049", "#8fbf5e"],
    season: [6, 7, 8],
    motif: "fan",
    tags: ["sweet", "juicy", "light", "fruity", "snappy"],
    note: "Cold, sweet, and the loudest pink available to you.",
    loves: ["feta", "mint", "prosciutto", "olive-oil"],
    cuts: [
      {
        name: "Batons with Feta",
        how: "Cut into fat fingers, crumble feta over, and finish with mint and cracked pepper.",
        motif: "batons",
        effort: 2,
      },
      {
        name: "Thin Triangles",
        how: "Slice into thin rind-on triangles and fan them so the green edge repeats.",
        motif: "fan",
        effort: 1,
      },
    ],
  },
  {
    id: "cherry-tomato",
    name: "Cherry tomatoes",
    cat: "veg",
    palette: ["#dc3f3a", "#bd2c2c", "#6ea24a"],
    season: [7, 8, 9],
    motif: "cluster",
    tags: ["acidic", "juicy", "sweet", "snappy", "grassy"],
    note: "On the vine if you can get them — the stem is half the look.",
    loves: ["mozzarella", "basil", "olive-oil", "burrata", "finocchiona"],
    cuts: [
      {
        name: "Left on the Vine",
        how: "Drape whole trusses across the board, stems intact. Don't pick them off.",
        motif: "cluster",
        flair: "A vine trailing over the board edge does more than any arrangement.",
        effort: 1,
      },
    ],
  },
  {
    id: "cucumber",
    name: "Cucumber",
    cat: "veg",
    palette: ["#8fbf5e", "#75a446", "#e2efc4"],
    motif: "shingle",
    tags: ["grassy", "snappy", "light", "juicy", "mild"],
    note: "Persian or Lebanese — small, seedless, actually crunchy.",
    loves: ["labneh", "feta", "hummus", "dill", "smoked-salmon"],
    cuts: [
      {
        name: "Bias Ovals",
        how: "Slice hard on the diagonal for long ovals, then shingle them in a run.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "radish",
    name: "Breakfast radishes",
    cat: "veg",
    palette: ["#e0426a", "#c22e54", "#fbf6ec"],
    season: [4, 5, 6],
    motif: "halved",
    tags: ["peppery", "snappy", "crunchy", "light", "bitter"],
    note: "Halved, with butter and flaky salt. The most French thing on the board.",
    loves: ["boursin", "flaky-salt", "labneh", "baguette"],
    cuts: [
      {
        name: "Halved, Tops On",
        how: "Halve lengthways through the leaves and serve with a dish of soft butter and salt.",
        motif: "halved",
        flair: "Leave an inch of green top on each. It's a handle and it's pretty.",
        effort: 1,
      },
    ],
  },
  {
    id: "endive",
    name: "Endive spears",
    cat: "veg",
    palette: ["#f4efd8", "#e4dcbc", "#c4d488"],
    motif: "fan",
    tags: ["bitter", "crunchy", "light", "snappy", "grassy"],
    note: "Nature's spoon. Bitter enough to stand up to a blue cheese.",
    loves: ["roquefort", "walnut", "pear", "chevre", "hummus"],
    cuts: [
      {
        name: "Separated Spears",
        how: "Break the head into individual leaves and fan them like a deck of cards, points outward.",
        motif: "fan",
        effort: 1,
      },
      {
        name: "Loaded Boats",
        how: "Fill each leaf with blue cheese, a walnut and a drip of honey. They travel well.",
        motif: "fan",
        effort: 2,
      },
    ],
  },
  {
    id: "snap-pea",
    name: "Sugar snap peas",
    cat: "veg",
    palette: ["#8fbf5e", "#72a244", "#c9e0a0"],
    season: [4, 5, 6],
    motif: "cluster",
    tags: ["grassy", "sweet", "snappy", "crunchy", "light"],
    note: "Raw and cold. The best crunch-to-effort ratio on any board.",
    loves: ["labneh", "boursin", "hummus", "mint"],
    cuts: [
      {
        name: "Whole & Raw",
        how: "Nothing. Pile them raw, pods on. Perhaps split a few open to show the peas.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "bell-pepper",
    name: "Sweet peppers",
    cat: "veg",
    palette: ["#e8a52c", "#d08a18", "#c73a34"],
    motif: "batons",
    tags: ["sweet", "crunchy", "juicy", "grassy", "light"],
    note: "Red, orange and yellow together, cut into strips. Cheap colour.",
    loves: ["hummus", "romesco", "feta", "muhammara"],
    cuts: [
      {
        name: "Colour-Sorted Strips",
        how: "Cut into batons and group by colour rather than mixing — the blocks read stronger.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "carrot",
    name: "Rainbow carrots",
    cat: "veg",
    palette: ["#e8862c", "#cf6c18", "#a8407c"],
    motif: "batons",
    tags: ["sweet", "crunchy", "earthy", "snappy", "light"],
    note: "Purple, yellow and orange. Buy them with the fronds attached.",
    loves: ["hummus", "labneh", "muhammara", "romesco"],
    cuts: [
      {
        name: "Split with Tops",
        how: "Halve lengthways leaving an inch of frond on. Skip the baby-carrot bag entirely.",
        motif: "batons",
        effort: 1,
      },
    ],
  },
  {
    id: "starfruit",
    name: "Starfruit",
    cat: "fruit",
    palette: ["#f2d94c", "#dcc22c", "#f7eca0"],
    motif: "shingle",
    tags: ["acidic", "tropical", "juicy", "light", "floral"],
    note: "Mostly bought for the shape, and that is a completely valid reason.",
    loves: ["chevre", "honeycomb", "mint"],
    cuts: [
      {
        name: "Star Slices",
        how: "Slice straight across into stars and lay them flat where they'll be seen.",
        motif: "shingle",
        flair: "Three or four, scattered. Any more and the trick wears off.",
        effort: 1,
      },
    ],
  },
  {
    id: "lychee",
    name: "Lychee",
    cat: "fruit",
    palette: ["#fbf2ec", "#eee0d6", "#c94a5e"],
    season: [6, 7],
    motif: "cluster",
    tags: ["sweet", "floral", "juicy", "tropical", "light"],
    note: "Perfumed and translucent. Peel a few and leave the rest in their shells.",
    loves: ["chevre", "mint", "raspberry"],
    cuts: [
      {
        name: "Half-Peeled",
        how: "Peel half of them and leave the rest whole so the rough red shells contrast with the pearly fruit.",
        motif: "cluster",
        effort: 2,
      },
    ],
  },
  {
    id: "passionfruit",
    name: "Passionfruit",
    cat: "fruit",
    palette: ["#e8a02c", "#cf8418", "#5e3a2c"],
    motif: "halved",
    tags: ["acidic", "tropical", "juicy", "floral", "bold"],
    note: "Halve it and spoon the pulp over soft cheese. Wildly aromatic.",
    loves: ["ricotta", "mascarpone", "chevre", "honeycomb"],
    cuts: [
      {
        name: "Halved, Spooned Over",
        how: "Cut in half and leave them cut-side up with a small spoon so people can pour the pulp themselves.",
        motif: "halved",
        effort: 1,
      },
    ],
  },
  {
    id: "pineapple",
    name: "Pineapple",
    cat: "fruit",
    palette: ["#f0c22c", "#d9a818", "#c4d488"],
    motif: "fan",
    tags: ["sweet", "acidic", "tropical", "juicy", "bold"],
    note: "Grilled, it caramelises and stops fighting the cheese.",
    loves: ["chevre", "hot-honey", "mint", "prosciutto"],
    cuts: [
      {
        name: "Grilled Batons",
        how: "Cut into fingers and grill until striped, then hit with lime and chilli while hot.",
        motif: "batons",
        effort: 3,
      },
    ],
  },
  {
    id: "clementine",
    name: "Clementines",
    cat: "fruit",
    palette: ["#f2922c", "#d97818", "#5e7d4c"],
    season: [11, 12, 1, 2],
    motif: "halved",
    tags: ["citrus", "sweet", "juicy", "acidic", "light"],
    note: "Leaves on if you can find them — they're the whole winter mood.",
    loves: ["chevre", "dark-chocolate", "pistachio", "ricotta"],
    cuts: [
      {
        name: "Half-Peeled with Leaves",
        how: "Peel a couple into loose spirals, halve some crosswise, leave a few whole with the leaf attached.",
        motif: "halved",
        effort: 1,
      },
    ],
  },
  {
    id: "physalis",
    name: "Physalis",
    cat: "fruit",
    palette: ["#e8952c", "#cf7a18", "#e0d4a8"],
    motif: "cluster",
    tags: ["acidic", "sweet", "tropical", "floral", "juicy"],
    note: "Cape gooseberry in a papery lantern. Peel the husk back into wings.",
    loves: ["dark-chocolate", "chevre", "mascarpone"],
    cuts: [
      {
        name: "Husks Peeled Back",
        how: "Fold the papery husk back into a star behind each berry and stand them up.",
        motif: "cluster",
        flair: "Fiddly, and worth it — nothing else on the board has that silhouette.",
        effort: 2,
      },
    ],
  },
  {
    id: "currants-red",
    name: "Redcurrants",
    cat: "fruit",
    palette: ["#d62c40", "#b81c30", "#8fa04c"],
    season: [6, 7, 8],
    motif: "cluster",
    tags: ["acidic", "berry", "juicy", "snappy", "light"],
    note: "Sharp little jewels on a stem. Drape whole strigs across pale cheese.",
    loves: ["brie", "chevre", "triple-creme", "honeycomb"],
    cuts: [
      {
        name: "Whole Strigs",
        how: "Never pick them off the stem. Lay whole strings across the cheese so they trail.",
        motif: "cluster",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-cranberry",
    name: "Dried cranberries",
    cat: "dried",
    palette: ["#b02638", "#921c2c", "#d95a68"],
    motif: "scatter",
    tags: ["acidic", "sweet", "chewy", "fruity", "berry"],
    note: "Sharp, red, and exactly the right size to fill the last gaps.",
    loves: ["wensleydale-cranberry", "brie", "pecan", "oat-cake"],
    cuts: [
      {
        name: "Scattered Last",
        how: "Sprinkle over the board once everything else is placed, into whatever seams remain.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-pear",
    name: "Dried pear",
    cat: "dried",
    palette: ["#e0c489", "#c9a968", "#f2e4c4"],
    motif: "shingle",
    tags: ["sweet", "chewy", "floral", "honeyed", "fruity"],
    note: "Whole halves, dried until leathery. Keeps the pear silhouette.",
    loves: ["roquefort", "stilton", "walnut", "comte"],
    cuts: [
      {
        name: "Fanned Halves",
        how: "Overlap the halves so the pear outline repeats down a line.",
        motif: "shingle",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-apple",
    name: "Dried apple rings",
    cat: "dried",
    palette: ["#eeddb8", "#dcc899", "#f7f0dc"],
    motif: "round",
    tags: ["sweet", "acidic", "chewy", "fruity", "light"],
    note: "Pale rings with the core hole intact. Reads as decoration.",
    loves: ["cheddar", "clothbound-cheddar", "walnut", "onion-jam"],
    cuts: [
      {
        name: "Stacked Rings",
        how: "Thread a few onto a cinnamon stick, or just stack them into a leaning tower.",
        motif: "round",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-strawberry",
    name: "Freeze-dried strawberries",
    cat: "dried",
    palette: ["#dc3448", "#bd2436", "#f2a0a8"],
    motif: "scatter",
    tags: ["acidic", "sweet", "crunchy", "berry", "light"],
    note: "Intensely red and startlingly crisp. Shatters rather than chews.",
    loves: ["dark-chocolate", "mascarpone", "brie", "amaretti"],
    cuts: [
      {
        name: "Crushed Over",
        how: "Crush a few into dust and scatter over a soft white cheese for a pink snowfall.",
        motif: "scatter",
        effort: 1,
      },
    ],
  },
  {
    id: "dried-pineapple",
    name: "Dried pineapple",
    cat: "dried",
    palette: ["#f0c02c", "#d9a618", "#f7dc82"],
    motif: "round",
    tags: ["sweet", "tropical", "chewy", "acidic", "bold"],
    note: "Bright yellow rings. The loudest thing in the dried-fruit aisle.",
    loves: ["chevre", "cashew", "hot-honey", "dried-mango"],
    cuts: [
      {
        name: "Torn Rings",
        how: "Tear the rings in half so they look handled rather than packaged.",
        motif: "round",
        effort: 1,
      },
    ],
  },
  {
    id: "turkish-fig",
    name: "Turkish figs",
    cat: "dried",
    palette: ["#c9a86e", "#b08e52", "#e2cf9e"],
    motif: "halved",
    tags: ["sweet", "chewy", "honeyed", "nutty", "earthy"],
    note: "Fatter and paler than Mission figs, and much more floral.",
    loves: ["stilton", "walnut", "honeycomb", "manchego", "ossau-iraty"],
    cuts: [
      {
        name: "Split & Stuffed",
        how: "Press each fig flat, split the top, and tuck in a walnut half so it sits proud.",
        motif: "halved",
        effort: 2,
      },
    ],
  },
];
